export const fuels = [
  {
    key: "Petrol",
    translations: {
      en: "Petrol",
      az: "Benzin",
      pl: "Benzyna",
      de: "Benzin",
      es: "Gasolina",
      pt: "Gasolina",
      tr: "Benzin",
      uk: "Бензин"
    }
  },
  {
    key: "Diesel",
    translations: {
      en: "Diesel",
      az: "Dizel",
      pl: "Diesel",
      de: "Diesel",
      es: "Diésel",
      pt: "Diesel",
      tr: "Dizel",
      uk: "Дизель"
    }
  },
  {
    key: "Hybrid",
    translations: {
      en: "Hybrid",
      az: "Hibrid",
      pl: "Hybryda",
      de: "Hybrid",
      es: "Híbrido",
      pt: "Híbrido",
      tr: "Hibrit",
      uk: "Гібрид"
    }
  },
  {
    key: "Plug-in Hybrid",
    translations: {
      en: "Plug-in Hybrid",
      az: "Plug-in Hibrid",
      pl: "Hybryda Plug-in",
      de: "Plug-in-Hybrid",
      es: "Híbrido Enchufable",
      pt: "Híbrido Plug-in",
      tr: "Plug-in Hibrit",
      uk: "Плагін-гібрид"
    }
  },
  {
    key: "Electric",
    translations: {
      en: "Electric",
      az: "Elektrik",
      pl: "Elektryczny",
      de: "Elektrisch",
      es: "Eléctrico",
      pt: "Elétrico",
      tr: "Elektrik",
      uk: "Електромобіль"
    }
  },
  {
    key: "CNG",
    translations: {
      en: "CNG",
      az: "CNG",
      pl: "CNG",
      de: "CNG",
      es: "GNL",
      pt: "GNV",
      tr: "CNG",
      uk: "КПГ"
    }
  },
  {
    key: "LPG",
    translations: {
      en: "LPG",
      az: "LPG",
      pl: "LPG",
      de: "LPG",
      es: "GLP",
      pt: "GLP",
      tr: "LPG",
      uk: "ЗВГ"
    }
  },
  {
    key: "Hydrogen",
    translations: {
      en: "Hydrogen",
      az: "Hidrogen",
      pl: "Wodór",
      de: "Wasserstoff",
      es: "Hidrógeno",
      pt: "Hidrogênio",
      tr: "Hidrojen",
      uk: "Водень"
    }
  },
  {
    key: "Ethanol",
    translations: {
      en: "Ethanol",
      az: "Etanol",
      pl: "Etanol",
      de: "Ethanol",
      es: "Etanol",
      pt: "Etanol",
      tr: "Etanol",
      uk: "Етанол"
    }
  },
  {
    key: "Methanol",
    translations: {
      en: "Methanol",
      az: "Metanol",
      pl: "Metanol",
      de: "Methanol",
      es: "Metanol",
      pt: "Metanol",
      tr: "Metanol",
      uk: "Метанол"
    }
  },
  {
    key: "Biofuel",
    translations: {
      en: "Biofuel",
      az: "Biofuel",
      pl: "Biopaliwo",
      de: "Biokraftstoff",
      es: "Biocombustible",
      pt: "Biocombustível",
      tr: "Biyoyakıt",
      uk: "Біопаливо"
    }
  }
];

export const gearboxOptions = [
  { key: "Manual", translations: { en: "Manual", az: "Mexaniki", pl: "Manualna", de: "Manuell", es: "Manual", pt: "Manual", tr: "Manuel", uk: "Механіка" } },
  { key: "Automatic", translations: { en: "Automatic", az: "Avtomatik", pl: "Automatyczna", de: "Automatik", es: "Automático", pt: "Automático", tr: "Otomatik", uk: "Автомат" } },
  { key: "Dual-clutch", translations: { en: "Dual-clutch", az: "İkili-qatlı", pl: "Dwusprzęgłowa", de: "Doppelkupplung", es: "Doble Embrague", pt: "Dupla Embreagem", tr: "Çift Kavramalı", uk: "Робот" } },
  { key: "eCVT", translations: { en: "eCVT", az: "eCVT", pl: "eCVT", de: "eCVT", es: "eCVT", pt: "eCVT", tr: "eCVT", uk: "eCVT" } },
  { key: "Semi-automatic", translations: { en: "Semi-automatic", az: "Yarı avtomatik", pl: "Półautomatyczna", de: "Halbautomatik", es: "Semiautomático", pt: "Semiautomático", tr: "Yarı Otomatik", uk: "Напівавтомат" } }
];

export const conditions = [
  { key: "New", translations: { en: "New", az: "Yeni", pl: "Nowy", de: "Neu", es: "Nuevo", pt: "Novo", tr: "Sıfır", uk: "Новий" } },
  { key: "Used", translations: { en: "Used", az: "İstifadə olunmuş", pl: "Używany", de: "Gebraucht", es: "Usado", pt: "Usado", tr: "İkinci El", uk: "Вживаний" } },
  { key: "Certified", translations: { en: "Certified", az: "Sertifikatlı", pl: "Certyfikowany", de: "Zertifiziert", es: "Certificado", pt: "Certificado", tr: "Sertifikalı", uk: "Сертифікований" } },
  { key: "Repaired", translations: { en: "Repaired", az: "Təmir edilmiş", pl: "Naprawiony", de: "Repariert", es: "Reparado", pt: "Reparado", tr: "Tamirli", uk: "Відремонтований" } },
  { key: "Restored", translations: { en: "Restored", az: "Bərpa edilmiş", pl: "Odrestaurowany", de: "Restauriert", es: "Restaurado", pt: "Restaurado", tr: "Restore Edilmiş", uk: "Відновлений" } },
  { key: "Salvage", translations: { en: "Salvage", az: "Salvage", pl: "Wrak", de: "Schrott", es: "Siniestro", pt: "Sucata", tr: "Hasar Kayıtlı", uk: "Аварійний" } },
  { key: "Rebuild", translations: { en: "Rebuild", az: "Rebuild", pl: "Odbudowany", de: "Wiederaufgebaut", es: "Reconstruido", pt: "Reconstruído", tr: "Yeniden İmal Edilmiş", uk: "Перероблений" } }
];

export const colors = [
  { key: "Black", translations: { en: "Black", az: "Qara", pl: "Czarny", de: "Schwarz", es: "Negro", pt: "Preto", tr: "Siyah", uk: "Чорний" } },
  { key: "White", translations: { en: "White", az: "Ağ", pl: "Biały", de: "Weiß", es: "Blanco", pt: "Branco", tr: "Beyaz", uk: "Білий" } },
  { key: "Silver", translations: { en: "Silver", az: "Gümüşü", pl: "Srebrny", de: "Silber", es: "Plateado", pt: "Prata", tr: "Gümüş", uk: "Сріблястий" } },
  { key: "Gray", translations: { en: "Gray", az: "Boz", pl: "Szary", de: "Grau", es: "Gris", pt: "Cinza", tr: "Gri", uk: "Сірий" } },
  { key: "Red", translations: { en: "Red", az: "Qırmızı", pl: "Czerwony", de: "Rot", es: "Rojo", pt: "Vermelho", tr: "Kırmızı", uk: "Червоний" } },
  { key: "Blue", translations: { en: "Blue", az: "Mavi", pl: "Niebieski", de: "Blau", es: "Azul", pt: "Azul", tr: "Mavi", uk: "Синій" } },
  { key: "Green", translations: { en: "Green", az: "Yaşıl", pl: "Zielony", de: "Grün", es: "Verde", pt: "Verde", tr: "Yeşil", uk: "Зелений" } },
  { key: "Yellow", translations: { en: "Yellow", az: "Sarı", pl: "Żółty", de: "Gelb", es: "Amarillo", pt: "Amarelo", tr: "Sarı", uk: "Жовтий" } },
  { key: "Orange", translations: { en: "Orange", az: "Narıncı", pl: "Pomarańczowy", de: "Orange", es: "Naranja", pt: "Laranja", tr: "Turuncu", uk: "Помаранчевий" } },
  { key: "Brown", translations: { en: "Brown", az: "Qəhvəyi", pl: "Brązowy", de: "Braun", es: "Marrón", pt: "Marrom", tr: "Kahverengi", uk: "Коричневий" } },
  { key: "Beige", translations: { en: "Beige", az: "Bej", pl: "Beżowy", de: "Beige", es: "Beige", pt: "Bege", tr: "Bej", uk: "Бежевий" } },
  { key: "Gold", translations: { en: "Gold", az: "Qızılı", pl: "Złoty", de: "Gold", es: "Dorado", pt: "Dourado", tr: "Altın", uk: "Золотий" } },
  { key: "Purple", translations: { en: "Purple", az: "Bənövşəyi", pl: "Fioletowy", de: "Lila", es: "Púrpura", pt: "Roxo", tr: "Mor", uk: "Фіолетовий" } },
  { key: "Lavender", translations: { en: "Lavender", az: "Lavanda", pl: "Lawendowy", de: "Lavendel", es: "Lavanda", pt: "Lavanda", tr: "Lavanta", uk: "Лавандовий" } },
  { key: "Pink", translations: { en: "Pink", az: "Çəhrayı", pl: "Różowy", de: "Rosa", es: "Rosa", pt: "Rosa", tr: "Pembe", uk: "Рожевий" } },
  { key: "Bordeaux", translations: { en: "Bordeaux", az: "Bordo", pl: "Bordowy", de: "Bordeaux", es: "Burdeos", pt: "Bordeaux", tr: "Bordo", uk: "Бордовий" } },
  { key: "Dark Blue", translations: { en: "Dark Blue", az: "Tünd Mavi", pl: "Ciemnoniebieski", de: "Dunkelblau", es: "Azul Oscuro", pt: "Azul Escuro", tr: "Lacivert", uk: "Темно-синій" } },
  { key: "Olive", translations: { en: "Olive", az: "Zeytun", pl: "Oliwkowy", de: "Oliv", es: "Oliva", pt: "Oliva", tr: "Zeytin Yeşili", uk: "Оливковий" } },
  { key: "Turquoise", translations: { en: "Turquoise", az: "Türkuaz", pl: "Turkusowy", de: "Türkis", es: "Turquesa", pt: "Turquesa", tr: "Turkuaz", uk: "Бірюзовий" } },
  { key: "Magenta", translations: { en: "Magenta", az: "Magenta", pl: "Magenta", de: "Magenta", es: "Magenta", pt: "Magenta", tr: "Macenta", uk: "Пурпурний" } },
  { key: "Cream", translations: { en: "Cream", az: "Krem", pl: "Kremowy", de: "Creme", es: "Crema", pt: "Creme", tr: "Krem", uk: "Кремовий" } },
  { key: "Peach", translations: { en: "Peach", az: "Şaftalı", pl: "Brzoskwiniowy", de: "Pfirsich", es: "Durazno", pt: "Pêssego", tr: "Şeftali", uk: "Персиковий" } },
  { key: "Tan", translations: { en: "Tan", az: "Tan", pl: "Płowy", de: "Hautfarben", es: "Bronceado", pt: "Bronzeado", tr: "Ten", uk: "Загорілий" } },
  { key: "Chocolate", translations: { en: "Chocolate", az: "Şokolad", pl: "Czekoladowy", de: "Schokoladenbraun", es: "Chocolate", pt: "Chocolate", tr: "Çikolata", uk: "Шоколадний" } },
  { key: "Bronze", translations: { en: "Bronze", az: "Bürünc", pl: "Brązowy", de: "Bronze", es: "Bronce", pt: "Bronze", tr: "Bronz", uk: "Бронзовий" } },
  { key: "Rose", translations: { en: "Rose", az: "Gül", pl: "Różany", de: "Rosen", es: "Rosa", pt: "Rosa", tr: "Gül", uk: "Трояндовий" } },
  { key: "Mint", translations: { en: "Mint", az: "Nanə", pl: "Miętowy", de: "Minzgrün", es: "Menta", pt: "Menta", tr: "Nane", uk: "М'ятний" } },
  { key: "Apricot", translations: { en: "Apricot", az: "Aprikot", pl: "Morelowy", de: "Aprikose", es: "Albaricoque", pt: "Damasco", tr: "Kayısı", uk: "Абрикосовий" } },
  { key: "Charcoal", translations: { en: "Charcoal", az: "Kömür Boz", pl: "Węglowy", de: "Kohlegrau", es: "Carbón", pt: "Carvão", tr: "Kömür Grisi", uk: "Вугільний" } },
  { key: "Teal", translations: { en: "Teal", az: "Teal", pl: "Morski", de: "Blaugrün", es: "Verde Azulado", pt: "Azul Esverdeado", tr: "Teal", uk: "Бірюзовий" } },
  { key: "Indigo", translations: { en: "Indigo", az: "Indigo", pl: "Indygo", de: "Indigo", es: "Índigo", pt: "Índigo", tr: "Çivit Mavisi", uk: "Індиго" } },
  { key: "Emerald", translations: { en: "Emerald", az: "Smaragd", pl: "Szmaragdowy", de: "Smaragdgrün", es: "Esmeralda", pt: "Esmeralda", tr: "Zümrüt Yeşili", uk: "Смарагдовий" } },
  { key: "Sapphire", translations: { en: "Sapphire", az: "Safir", pl: "Szafirowy", de: "Saphirblau", es: "Zafiro", pt: "Safira", tr: "Safir Mavisi", uk: "Сапфіровий" } },
  { key: "Ruby", translations: { en: "Ruby", az: "Rubin", pl: "Rubinowy", de: "Rubinrot", es: "Rubí", pt: "Rubi", tr: "Yakut Kırmızısı", uk: "Рубіновий" } },
  { key: "Amber", translations: { en: "Amber", az: "Amber", pl: "Bursztynowy", de: "Bernstein", es: "Ámbar", pt: "Âmbar", tr: "Kehribar", uk: "Бурштиновий" } },
  { key: "Sand", translations: { en: "Sand", az: "Qum", pl: "Piaskowy", de: "Sandfarben", es: "Arena", pt: "Areia", tr: "Kum", uk: "Піщаний" } },
  { key: "Rust", translations: { en: "Rust", az: "Pas", pl: "Rdzawny", de: "Rost", es: "Óxido", pt: "Ferrugem", tr: "Pas", uk: "Іржавий" } },
  { key: "Jade", translations: { en: "Jade", az: "Jad", pl: "Jadeitowy", de: "Jade", es: "Jade", pt: "Jade", tr: "Yeşim", uk: "Нефритовий" } },
  { key: "Alabaster", translations: { en: "Alabaster", az: "Alabaster", pl: "Alabastrowy", de: "Alabaster", es: "Alabastro", pt: "Alabastro", tr: "Alabaster", uk: "Алебастровий" } },
  { key: "Opal", translations: { en: "Opal", az: "Opal", pl: "Opalowy", de: "Opal", es: "Ópalo", pt: "Opala", tr: "Opal", uk: "Опаловий" } },
  { key: "Graphite", translations: { en: "Graphite", az: "Qrafit", pl: "Grafitowy", de: "Graphit", es: "Grafito", pt: "Grafite", tr: "Grafit", uk: "Графітовий" } }
];

export const bodyTypes = [
  { key: "Sedan", translations: { en: "Sedan", az: "Sedan", pl: "Sedan", de: "Limousine", es: "Sedán", pt: "Sedan", tr: "Sedan", uk: "Седан" } },
  { key: "Hatchback", translations: { en: "Hatchback", az: "Hatchback", pl: "Hatchback", de: "Heckklappe", es: "Hatchback", pt: "Hatchback", tr: "Hatchback", uk: "Хетчбек" } },
  { key: "SUV", translations: { en: "SUV", az: "SUV", pl: "SUV", de: "SUV", es: "SUV", pt: "SUV", tr: "SUV", uk: "Позашляховик" } },
  { key: "Crossover", translations: { en: "Crossover", az: "Crossover", pl: "Crossover", de: "Crossover", es: "Crossover", pt: "Crossover", tr: "Crossover", uk: "Кросовер" } },
  { key: "Coupe", translations: { en: "Coupe", az: "Coupe", pl: "Coupe", de: "Coupé", es: "Cupé", pt: "Cupê", tr: "Coupe", uk: "Купе" } },
  { key: "Convertible", translations: { en: "Convertible", az: "Convertible", pl: "Kabriolet", de: "Cabrio", es: "Convertible", pt: "Conversível", tr: "Cabrio", uk: "Кабріолет" } },
  { key: "Van", translations: { en: "Van", az: "Van", pl: "Van", de: "Van", es: "Furgoneta", pt: "Van", tr: "Van", uk: "Фургон" } },
  { key: "Minivan", translations: { en: "Minivan", az: "Minivan", pl: "Minivan", de: "Minivan", es: "Minivan", pt: "Minivan", tr: "Minivan", uk: "Мінівен" } },
  { key: "Pickup", translations: { en: "Pickup", az: "Pickup", pl: "Pickup", de: "Pick-up", es: "Pick-up", pt: "Picape", tr: "Pickup", uk: "Пікап" } },
  { key: "Wagon", translations: { en: "Wagon", az: "Wagon", pl: "Kombi", de: "Kombi", es: "Familiar", pt: "Perua", tr: "Station Wagon", uk: "Універсал" } },
  { key: "City car", translations: { en: "City car", az: "Şəhər avtomobili", pl: "Miejski", de: "Stadtwagen", es: "Auto Urbano", pt: "Carro Urbano", tr: "Şehir Arabası", uk: "Міський автомобіль" } },
  { key: "Microcar", translations: { en: "Microcar", az: "Mikroavtomobil", pl: "Mikrosamochód", de: "Mikroauto", es: "Microcoche", pt: "Microcarro", tr: "Mikro Araba", uk: "Мікрокар" } },
  { key: "Roadster", translations: { en: "Roadster", az: "Roadster", pl: "Roadster", de: "Roadster", es: "Roadster", pt: "Roadster", tr: "Roadster", uk: "Родстер" } },
  { key: "Targa", translations: { en: "Targa", az: "Targa", pl: "Targa", de: "Targa", es: "Targa", pt: "Targa", tr: "Targa", uk: "Тарга" } },
  { key: "Shooting Brake", translations: { en: "Shooting Brake", az: "Shooting Brake", pl: "Shooting Brake", de: "Shooting Brake", es: "Shooting Brake", pt: "Shooting Brake", tr: "Shooting Brake", uk: "Шутінг-брейк" } },
  { key: "Fastback", translations: { en: "Fastback", az: "Fastback", pl: "Fastback", de: "Fastback", es: "Fastback", pt: "Fastback", tr: "Fastback", uk: "Фастбек" } },
  { key: "Liftback", translations: { en: "Liftback", az: "Liftback", pl: "Liftback", de: "Liftback", es: "Liftback", pt: "Liftback", tr: "Liftback", uk: "Ліфтбек" } },
  { key: "Panel Van", translations: { en: "Panel Van", az: "Panel Van", pl: "Furgon", de: "Kastenwagen", es: "Furgoneta", pt: "Furgão", tr: "Panel Van", uk: "Фургон" } },
  { key: "Box Truck", translations: { en: "Box Truck", az: "Box Truck", pl: "Samochód dostawczy", de: "Kastenfahrzeug", es: "Camión de Caja", pt: "Caminhão de Caixa", tr: "Kutu Kamyon", uk: "Вантажівка" } },
  { key: "Crew Cab", translations: { en: "Crew Cab", az: "Crew Cab", pl: "Podwójna kabina", de: "Doppelkabine", es: "Cabina Doble", pt: "Cabine Dupla", tr: "Çift Kabin", uk: "Подвійна кабіна" } },
  { key: "Extended Cab", translations: { en: "Extended Cab", az: "Extended Cab", pl: "Przedłużona kabina", de: "Erweiterte Kabine", es: "Cabina Extendida", pt: "Cabine Estendida", tr: "Uzatılmış Kabin", uk: "Розширена кабіна" } }
];

export const engineOptions = [
  { key: "0.6L", translations: { en: "0.6L", az: "0.6L", pl: "0.6L", de: "0.6L", es: "0.6L", pt: "0.6L", tr: "0.6L", uk: "0.6L" } },
  { key: "0.8L", translations: { en: "0.8L", az: "0.8L", pl: "0.8L", de: "0.8L", es: "0.8L", pt: "0.8L", tr: "0.8L", uk: "0.8L" } },
  { key: "1.0L", translations: { en: "1.0L", az: "1.0L", pl: "1.0L", de: "1.0L", es: "1.0L", pt: "1.0L", tr: "1.0L", uk: "1.0L" } },
  { key: "1.2L", translations: { en: "1.2L", az: "1.2L", pl: "1.2L", de: "1.2L", es: "1.2L", pt: "1.2L", tr: "1.2L", uk: "1.2L" } },
  { key: "1.3L", translations: { en: "1.3L", az: "1.3L", pl: "1.3L", de: "1.3L", es: "1.3L", pt: "1.3L", tr: "1.3L", uk: "1.3L" } },
  { key: "1.4L", translations: { en: "1.4L", az: "1.4L", pl: "1.4L", de: "1.4L", es: "1.4L", pt: "1.4L", tr: "1.4L", uk: "1.4L" } },
  { key: "1.5L", translations: { en: "1.5L", az: "1.5L", pl: "1.5L", de: "1.5L", es: "1.5L", pt: "1.5L", tr: "1.5L", uk: "1.5L" } },
  { key: "1.6L", translations: { en: "1.6L", az: "1.6L", pl: "1.6L", de: "1.6L", es: "1.6L", pt: "1.6L", tr: "1.6L", uk: "1.6L" } },
  { key: "1.8L", translations: { en: "1.8L", az: "1.8L", pl: "1.8L", de: "1.8L", es: "1.8L", pt: "1.8L", tr: "1.8L", uk: "1.8L" } },
  { key: "2.0L", translations: { en: "2.0L", az: "2.0L", pl: "2.0L", de: "2.0L", es: "2.0L", pt: "2.0L", tr: "2.0L", uk: "2.0L" } },
  { key: "2.2L", translations: { en: "2.2L", az: "2.2L", pl: "2.2L", de: "2.2L", es: "2.2L", pt: "2.2L", tr: "2.2L", uk: "2.2L" } },
  { key: "2.4L", translations: { en: "2.4L", az: "2.4L", pl: "2.4L", de: "2.4L", es: "2.4L", pt: "2.4L", tr: "2.4L", uk: "2.4L" } },
  { key: "2.5L", translations: { en: "2.5L", az: "2.5L", pl: "2.5L", de: "2.5L", es: "2.5L", pt: "2.5L", tr: "2.5L", uk: "2.5L" } },
  { key: "3.0L", translations: { en: "3.0L", az: "3.0L", pl: "3.0L", de: "3.0L", es: "3.0L", pt: "3.0L", tr: "3.0L", uk: "3.0L" } },
  { key: "3.5L", translations: { en: "3.5L", az: "3.5L", pl: "3.5L", de: "3.5L", es: "3.5L", pt: "3.5L", tr: "3.5L", uk: "3.5L" } },
  { key: "4.0L", translations: { en: "4.0L", az: "4.0L", pl: "4.0L", de: "4.0L", es: "4.0L", pt: "4.0L", tr: "4.0L", uk: "4.0L" } },
  { key: "4.4L", translations: { en: "4.4L", az: "4.4L", pl: "4.4L", de: "4.4L", es: "4.4L", pt: "4.4L", tr: "4.4L", uk: "4.4L" } },
  { key: "5.0L", translations: { en: "5.0L", az: "5.0L", pl: "5.0L", de: "5.0L", es: "5.0L", pt: "5.0L", tr: "5.0L", uk: "5.0L" } },
  { key: "6.0L", translations: { en: "6.0L", az: "6.0L", pl: "6.0L", de: "6.0L", es: "6.0L", pt: "6.0L", tr: "6.0L", uk: "6.0L" } },
  { key: "Electric (kW)", translations: { en: "Electric (kW)", az: "Elektrik (kW)", pl: "Elektryczny (kW)", de: "Elektrisch (kW)", es: "Eléctrico (kW)", pt: "Elétrico (kW)", tr: "Elektrik (kW)", uk: "Електричний (кВт)" } },
  { key: "Hybrid (mild)", translations: { en: "Hybrid (mild)", az: "Hibrid (mild)", pl: "Hybryda (mild)", de: "Hybrid (mild)", es: "Híbrido (suave)", pt: "Híbrido (suave)", tr: "Hibrit (hafif)", uk: "Гібрид (м'який)" } },
  { key: "Plug-in Hybrid", translations: { en: "Plug-in Hybrid", az: "Plug-in Hibrid", pl: "Hybryda Plug-in", de: "Plug-in-Hybrid", es: "Híbrido Enchufable", pt: "Híbrido Plug-in", tr: "Plug-in Hibrit", uk: "Плагін-гібрид" } },
  { key: "Rotary", translations: { en: "Rotary", az: "Rotary", pl: "Rotacyjny", de: "Rotationsmotor", es: "Rotativo", pt: "Rotativo", tr: "Rotary", uk: "Роторний" } },
  { key: "Diesel Turbo", translations: { en: "Diesel Turbo", az: "Dizel Turbo", pl: "Diesel Turbo", de: "Diesel Turbo", es: "Diésel Turbo", pt: "Diesel Turbo", tr: "Dizel Turbo", uk: "Дизель турбо" } },
  { key: "Bi-Turbo", translations: { en: "Bi-Turbo", az: "Bi-Turbo", pl: "Bi-Turbo", de: "Bi-Turbo", es: "Bi-Turbo", pt: "Bi-Turbo", tr: "Bi-Turbo", uk: "Бі-турбо" } },
  { key: "Twin-Turbo", translations: { en: "Twin-Turbo", az: "Twin-Turbo", pl: "Twin-Turbo", de: "Twin-Turbo", es: "Twin-Turbo", pt: "Twin-Turbo", tr: "Twin-Turbo", uk: "Твін-турбо" } }
];

export const cities = [
  { key: "Augustów", translations: { en: "Augustow", az: "Auqustov", pl: "Augustów", de: "Augustow", es: "Augustow", pt: "Augustow", tr: "Augustow", uk: "Августів" } },
  { key: "Biała Podlaska", translations: { en: "Biala Podlaska", az: "Biala Podlaska", pl: "Biała Podlaska", de: "Biala Podlaska", es: "Biala Podlaska", pt: "Biala Podlaska", tr: "Biala Podlaska", uk: "Біла Підляська" } },
  { key: "Białystok", translations: { en: "Bialystok", az: "Bialistok", pl: "Białystok", de: "Bialystok", es: "Bialystok", pt: "Bialystok", tr: "Bialystok", uk: "Білосток" } },
  { key: "Bielawa", translations: { en: "Bielawa", az: "Bielava", pl: "Bielawa", de: "Bielawa", es: "Bielawa", pt: "Bielawa", tr: "Bielawa", uk: "Белява" } },
  { key: "Bielsko-Biała", translations: { en: "Bielsko-Biala", az: "Belsko-Biala", pl: "Bielsko-Biała", de: "Bielsko-Biala", es: "Bielsko-Biala", pt: "Bielsko-Biala", tr: "Bielsko-Biala", uk: "Бельсько-Бяла" } },
  { key: "Bolesławiec", translations: { en: "Boleslawiec", az: "Boleslavets", pl: "Bolesławiec", de: "Boleslawiec", es: "Boleslawiec", pt: "Boleslawiec", tr: "Boleslawiec", uk: "Болеславець" } },
  { key: "Bochnia", translations: { en: "Bochnia", az: "Boxniya", pl: "Bochnia", de: "Bochnia", es: "Bochnia", pt: "Bochnia", tr: "Bochnia", uk: "Бохня" } },
  { key: "Braniewo", translations: { en: "Braniewo", az: "Branevo", pl: "Braniewo", de: "Braniewo", es: "Braniewo", pt: "Braniewo", tr: "Braniewo", uk: "Бранево" } },
  { key: "Bytom", translations: { en: "Bytom", az: "Bitom", pl: "Bytom", de: "Bytom", es: "Bytom", pt: "Bytom", tr: "Bytom", uk: "Битом" } },
  { key: "Bydgoszcz", translations: { en: "Bydgoszcz", az: "Bidqoşç", pl: "Bydgoszcz", de: "Bydgoszcz", es: "Bydgoszcz", pt: "Bydgoszcz", tr: "Bydgoszcz", uk: "Бидгощ" } },
  { key: "Chełm", translations: { en: "Chelm", az: "Helm", pl: "Chełm", de: "Chelm", es: "Chelm", pt: "Chelm", tr: "Chelm", uk: "Холм" } },
  { key: "Chojnice", translations: { en: "Chojnice", az: "Xoynitse", pl: "Chojnice", de: "Chojnice", es: "Chojnice", pt: "Chojnice", tr: "Chojnice", uk: "Хойніце" } },
  { key: "Chorzów", translations: { en: "Chorzow", az: "Xorjov", pl: "Chorzów", de: "Chorzow", es: "Chorzow", pt: "Chorzow", tr: "Chorzow", uk: "Хожув" } },
  { key: "Chrzanów", translations: { en: "Chrzanow", az: "Xrjanov", pl: "Chrzanów", de: "Chrzanow", es: "Chrzanow", pt: "Chrzanow", tr: "Chrzanow", uk: "Хшанов" } },
  { key: "Czarnków", translations: { en: "Czarnkow", az: "Çarnkov", pl: "Czarnków", de: "Czarnkow", es: "Czarnkow", pt: "Czarnkow", tr: "Czarnkow", uk: "Чарнкув" } },
  { key: "Częstochowa", translations: { en: "Czestochowa", az: "Çenstoxova", pl: "Częstochowa", de: "Tschenstochau", es: "Czestochowa", pt: "Czestochowa", tr: "Czestochowa", uk: "Ченстохова" } },
  { key: "Dąbrowa Górnicza", translations: { en: "Dabrowa Gornicza", az: "Dombrova Qurniça", pl: "Dąbrowa Górnicza", de: "Dabrowa Gornicza", es: "Dabrowa Gornicza", pt: "Dabrowa Gornicza", tr: "Dabrowa Gornicza", uk: "Домброва-Гурнича" } },
  { key: "Dębica", translations: { en: "Debica", az: "Dembitsa", pl: "Dębica", de: "Debica", es: "Debica", pt: "Debica", tr: "Debica", uk: "Дембиця" } },
  { key: "Elbląg", translations: { en: "Elblag", az: "Elblonq", pl: "Elbląg", de: "Elbing", es: "Elblag", pt: "Elblag", tr: "Elblag", uk: "Ельблонг" } },
  { key: "Ełk", translations: { en: "Elk", az: "Elk", pl: "Ełk", de: "Lyck", es: "Elk", pt: "Elk", tr: "Elk", uk: "Елк" } },
  { key: "Gdańsk", translations: { en: "Gdansk", az: "Qdansk", pl: "Gdańsk", de: "Danzig", es: "Gdansk", pt: "Gdansk", tr: "Gdansk", uk: "Гданськ" } },
  { key: "Gdynia", translations: { en: "Gdynia", az: "Qdiniya", pl: "Gdynia", de: "Gdingen", es: "Gdynia", pt: "Gdynia", tr: "Gdynia", uk: "Гдиня" } },
  { key: "Giżycko", translations: { en: "Gizycko", az: "Gijitsko", pl: "Giżycko", de: "Lötzen", es: "Gizycko", pt: "Gizycko", tr: "Gizycko", uk: "Гіжицько" } },
  { key: "Głogów", translations: { en: "Glogow", az: "Qloqov", pl: "Głogów", de: "Glogau", es: "Glogow", pt: "Glogow", tr: "Glogow", uk: "Глогув" } },
  { key: "Gniezno", translations: { en: "Gniezno", az: "Qnyezno", pl: "Gniezno", de: "Gnesen", es: "Gniezno", pt: "Gniezno", tr: "Gniezno", uk: "Гнєзно" } },
  { key: "Gorlice", translations: { en: "Gorlice", az: "Qorlitse", pl: "Gorlice", de: "Gorlice", es: "Gorlice", pt: "Gorlice", tr: "Gorlice", uk: "Горлиці" } },
  { key: "Grudziądz", translations: { en: "Grudziadz", az: "Qrudzyadz", pl: "Grudziądz", de: "Graudenz", es: "Grudziadz", pt: "Grudziadz", tr: "Grudziadz", uk: "Грудзьондз" } },
  { key: "Gryfice", translations: { en: "Gryfice", az: "Qrifitse", pl: "Gryfice", de: "Greifenberg", es: "Gryfice", pt: "Gryfice", tr: "Gryfice", uk: "Грифиці" } },
  { key: "Iława", translations: { en: "Ilawa", az: "İlava", pl: "Iława", de: "Deutsch Eylau", es: "Ilawa", pt: "Ilawa", tr: "Ilawa", uk: "Ілава" } },
  { key: "Inowrocław", translations: { en: "Inowroclaw", az: "İnovrotslav", pl: "Inowrocław", de: "Inowrazlaw", es: "Inowroclaw", pt: "Inowroclaw", tr: "Inowroclaw", uk: "Іновроцлав" } },
  { key: "Jarosław", translations: { en: "Jaroslaw", az: "Yaroslav", pl: "Jarosław", de: "Jaroslau", es: "Jaroslaw", pt: "Jaroslaw", tr: "Jaroslaw", uk: "Ярослав" } },
  { key: "Jastrzębie-Zdrój", translations: { en: "Jastrzebie-Zdroj", az: "Yastrjembye-Zdroy", pl: "Jastrzębie-Zdrój", de: "Bad Königsdorff-Jastrzemb", es: "Jastrzebie-Zdroj", pt: "Jastrzebie-Zdroj", tr: "Jastrzebie-Zdroj", uk: "Ястшембе-Здруй" } },
  { key: "Jaworzno", translations: { en: "Jaworzno", az: "Yavorjno", pl: "Jaworzno", de: "Jaworzno", es: "Jaworzno", pt: "Jaworzno", tr: "Jaworzno", uk: "Явожно" } },
  { key: "Jelenia Góra", translations: { en: "Jelenia Gora", az: "Yelenya Qura", pl: "Jelenia Góra", de: "Hirschberg", es: "Jelenia Gora", pt: "Jelenia Gora", tr: "Jelenia Gora", uk: "Єленя-Гура" } },
  { key: "Kalisz", translations: { en: "Kalisz", az: "Kaliş", pl: "Kalisz", de: "Kalisch", es: "Kalisz", pt: "Kalisz", tr: "Kalisz", uk: "Каліш" } },
  { key: "Kartuzy", translations: { en: "Kartuzy", az: "Kartuzi", pl: "Kartuzy", de: "Karthaus", es: "Kartuzy", pt: "Kartuzy", tr: "Kartuzy", uk: "Картузи" } },
  { key: "Kędzierzyn-Koźle", translations: { en: "Kedzierzyn-Kozle", az: "Kendjersin-Kozle", pl: "Kędzierzyn-Koźle", de: "Kandrzin-Cosel", es: "Kedzierzyn-Kozle", pt: "Kedzierzyn-Kozle", tr: "Kedzierzyn-Kozle", uk: "Кендзежин-Козле" } },
  { key: "Kielce", translations: { en: "Kielce", az: "Kelçe", pl: "Kielce", de: "Kielce", es: "Kielce", pt: "Kielce", tr: "Kielce", uk: "Кельце" } },
  { key: "Konin", translations: { en: "Konin", az: "Konin", pl: "Konin", de: "Konin", es: "Konin", pt: "Konin", tr: "Konin", uk: "Конін" } },
  { key: "Koszalin", translations: { en: "Koszalin", az: "Koşalin", pl: "Koszalin", de: "Köslin", es: "Koszalin", pt: "Koszalin", tr: "Koszalin", uk: "Кошалін" } },
  { key: "Krosno", translations: { en: "Krosno", az: "Krosno", pl: "Krosno", de: "Krossen", es: "Krosno", pt: "Krosno", tr: "Krosno", uk: "Кросно" } },
  { key: "Kraków", translations: { en: "Krakow", az: "Krakov", pl: "Kraków", de: "Krakau", es: "Cracovia", pt: "Cracóvia", tr: "Krakow", uk: "Краків" } },
  { key: "Krosno Odrzańskie", translations: { en: "Krosno Odzanskie", az: "Krosno Odjanske", pl: "Krosno Odrzańskie", de: "Crossen an der Oder", es: "Krosno Odzanskie", pt: "Krosno Odzanskie", tr: "Krosno Odzanskie", uk: "Кросно-Оджанське" } },
  { key: "Kutno", translations: { en: "Kutno", az: "Kutno", pl: "Kutno", de: "Kutno", es: "Kutno", pt: "Kutno", tr: "Kutno", uk: "Кутно" } },
  { key: "Kwidzyn", translations: { en: "Kwidzyn", az: "Kvidzin", pl: "Kwidzyn", de: "Marienwerder", es: "Kwidzyn", pt: "Kwidzyn", tr: "Kwidzyn", uk: "Квідзин" } },
  { key: "Lębork", translations: { en: "Lebork", az: "Lebork", pl: "Lębork", de: "Lauenburg", es: "Lebork", pt: "Lebork", tr: "Lebork", uk: "Лемборк" } },
  { key: "Legnica", translations: { en: "Legnica", az: "Leqnitsa", pl: "Legnica", de: "Liegnitz", es: "Legnica", pt: "Legnica", tr: "Legnica", uk: "Легниця" } },
  { key: "Leszno", translations: { en: "Leszno", az: "Leşno", pl: "Leszno", de: "Lissa", es: "Leszno", pt: "Leszno", tr: "Leszno", uk: "Лешно" } },
  { key: "Lublin", translations: { en: "Lublin", az: "Lublin", pl: "Lublin", de: "Lublin", es: "Lublin", pt: "Lublin", tr: "Lublin", uk: "Люблін" } },
  { key: "Łomża", translations: { en: "Lomza", az: "Lomja", pl: "Łomża", de: "Lomsha", es: "Lomza", pt: "Lomza", tr: "Lomza", uk: "Ломжа" } },
  { key: "Łódź", translations: { en: "Lodz", az: "Lodz", pl: "Łódź", de: "Lodz", es: "Lodz", pt: "Lodz", tr: "Lodz", uk: "Лодзь" } },
  { key: "Mielec", translations: { en: "Mielec", az: "Myelets", pl: "Mielec", de: "Mielec", es: "Mielec", pt: "Mielec", tr: "Mielec", uk: "Мелець" } },
  { key: "Mińsk Mazowiecki", translations: { en: "Minsk Mazowiecki", az: "Minisk Mazovyetski", pl: "Mińsk Mazowiecki", de: "Mińsk Mazowiecki", es: "Minsk Mazowiecki", pt: "Minsk Mazowiecki", tr: "Minsk Mazowiecki", uk: "Мінськ-Мазовецький" } },
  { key: "Mysłowice", translations: { en: "Myslowice", az: "Mısłovitse", pl: "Mysłowice", de: "Myslowitz", es: "Myslowice", pt: "Myslowice", tr: "Myslowice", uk: "Мисловиці" } },
  { key: "Nowy Sącz", translations: { en: "Nowy Sacz", az: "Novı Sanç", pl: "Nowy Sącz", de: "Neu Sandez", es: "Nowy Sacz", pt: "Nowy Sacz", tr: "Nowy Sacz", uk: "Новий Сонч" } },
  { key: "Nowy Targ", translations: { en: "Nowy Targ", az: "Novı Tarq", pl: "Nowy Targ", de: "Neumarkt", es: "Nowy Targ", pt: "Nowy Targ", tr: "Nowy Targ", uk: "Новий Тарг" } },
  { key: "Nowy Dwór Mazowiecki", translations: { en: "Nowy Dwor Mazowiecki", az: "Novı Dvor Mazovyetski", pl: "Nowy Dwór Mazowiecki", de: "Nowy Dwór Mazowiecki", es: "Nowy Dwor Mazowiecki", pt: "Nowy Dwor Mazowiecki", tr: "Nowy Dwor Mazowiecki", uk: "Новий Двор-Мазовецький" } },
  { key: "Nowy Tomyśl", translations: { en: "Nowy Tomysl", az: "Novı Tomisl", pl: "Nowy Tomyśl", de: "Neutomischel", es: "Nowy Tomysl", pt: "Nowy Tomysl", tr: "Nowy Tomysl", uk: "Новий Томишль" } },
  { key: "Nowa Sól", translations: { en: "Nowa Sol", az: "Nova Sol", pl: "Nowa Sól", de: "Neusalz", es: "Nowa Sol", pt: "Nowa Sol", tr: "Nowa Sol", uk: "Нова Суль" } },
  { key: "Olsztyn", translations: { en: "Olsztyn", az: "Olştın", pl: "Olsztyn", de: "Allenstein", es: "Olsztyn", pt: "Olsztyn", tr: "Olsztyn", uk: "Ольштин" } },
  { key: "Opole", translations: { en: "Opole", az: "Opole", pl: "Opole", de: "Oppeln", es: "Opole", pt: "Opole", tr: "Opole", uk: "Ополе" } },
  { key: "Ostrołęka", translations: { en: "Ostroleka", az: "Ostroleka", pl: "Ostrołęka", de: "Ostrolenka", es: "Ostroleka", pt: "Ostroleka", tr: "Ostroleka", uk: "Остроленка" } },
  { key: "Ostrów Wielkopolski", translations: { en: "Ostrow Wielkopolski", az: "Ostrov Vyelkopolski", pl: "Ostrów Wielkopolski", de: "Ostrowo", es: "Ostrow Wielkopolski", pt: "Ostrow Wielkopolski", tr: "Ostrow Wielkopolski", uk: "Острув-Великопольський" } },
  { key: "Oświęcim", translations: { en: "Oswiecim", az: "Oşventsım", pl: "Oświęcim", de: "Auschwitz", es: "Oswiecim", pt: "Oswiecim", tr: "Oswiecim", uk: "Освенцім" } },
  { key: "Otwock", translations: { en: "Otwock", az: "Otvosk", pl: "Otwock", de: "Otwock", es: "Otwock", pt: "Otwock", tr: "Otwock", uk: "Отвоцьк" } },
  { key: "Pabianice", translations: { en: "Pabianice", az: "Pabyanitse", pl: "Pabianice", de: "Pabianice", es: "Pabianice", pt: "Pabianice", tr: "Pabianice", uk: "Паб'яниці" } },
  { key: "Piekary Śląskie", translations: { en: "Piekary Slaskie", az: "Pekarı Slanske", pl: "Piekary Śląskie", de: "Deutsch Piekar", es: "Piekary Slaskie", pt: "Piekary Slaskie", tr: "Piekary Slaskie", uk: "Пекари-Сльонські" } },
  { key: "Piła", translations: { en: "Pila", az: "Pila", pl: "Piła", de: "Schneidemühl", es: "Pila", pt: "Pila", tr: "Pila", uk: "Пила" } },
  { key: "Piotrków Trybunalski", translations: { en: "Piotrkow Trybunalski", az: "Pyotrkov Tribunalski", pl: "Piotrków Trybunalski", de: "Petrikau", es: "Piotrkow Trybunalski", pt: "Piotrkow Trybunalski", tr: "Piotrkow Trybunalski", uk: "Пйотркув-Трибунальський" } },
  { key: "Płock", translations: { en: "Plock", az: "Plotsk", pl: "Płock", de: "Plock", es: "Plock", pt: "Plock", tr: "Plock", uk: "Плоцьк" } },
  { key: "Poznań", translations: { en: "Poznan", az: "Poznan", pl: "Poznań", de: "Posen", es: "Poznan", pt: "Poznan", tr: "Poznan", uk: "Познань" } },
  { key: "Przemyśl", translations: { en: "Przemysl", az: "Pşemisl", pl: "Przemyśl", de: "Przemysl", es: "Przemysl", pt: "Przemysl", tr: "Przemysl", uk: "Перемишль" } },
  { key: "Pruszków", translations: { en: "Pruszkow", az: "Prushkov", pl: "Pruszków", de: "Pruszkow", es: "Pruszkow", pt: "Pruszkow", tr: "Pruszkow", uk: "Прушкув" } },
  { key: "Puławy", translations: { en: "Pulawy", az: "Pulavi", pl: "Puławy", de: "Pulawy", es: "Pulawy", pt: "Pulawy", tr: "Pulawy", uk: "Пулави" } },
  { key: "Racibórz", translations: { en: "Raciborz", az: "Ratsiborj", pl: "Racibórz", de: "Ratibor", es: "Raciborz", pt: "Raciborz", tr: "Raciborz", uk: "Рацибуж" } },
  { key: "Radom", translations: { en: "Radom", az: "Radom", pl: "Radom", de: "Radom", es: "Radom", pt: "Radom", tr: "Radom", uk: "Радом" } },
  { key: "Rawa Mazowiecka", translations: { en: "Rawa Mazowiecka", az: "Rava Mazovyetska", pl: "Rawa Mazowiecka", de: "Rawa Mazowiecka", es: "Rawa Mazowiecka", pt: "Rawa Mazowiecka", tr: "Rawa Mazowiecka", uk: "Рава-Мазовецька" } },
  { key: "Rzeszów", translations: { en: "Rzeszow", az: "Jeşuv", pl: "Rzeszów", de: "Rzeszow", es: "Rzeszow", pt: "Rzeszow", tr: "Rzeszow", uk: "Жешув" } },
  { key: "Siedlce", translations: { en: "Siedlce", az: "Siedlse", pl: "Siedlce", de: "Siedlce", es: "Siedlce", pt: "Siedlce", tr: "Siedlce", uk: "Седльце" } },
  { key: "Siemianowice Śląskie", translations: { en: "Siemianowice Slaskie", az: "Semyanovitse Slanske", pl: "Siemianowice Śląskie", de: "Siemianowice", es: "Siemianowice Slaskie", pt: "Siemianowice Slaskie", tr: "Siemianowice Slaskie", uk: "Семяновице-Сльонські" } },
  { key: "Słupsk", translations: { en: "Slupsk", az: "Sluppsk", pl: "Słupsk", de: "Stolp", es: "Slupsk", pt: "Slupsk", tr: "Slupsk", uk: "Слупськ" } },
  { key: "Sosnowiec", translations: { en: "Sosnowiec", az: "Sosnovets", pl: "Sosnowiec", de: "Sosnowitz", es: "Sosnowiec", pt: "Sosnowiec", tr: "Sosnowiec", uk: "Сосновець" } },
  { key: "Stargard", translations: { en: "Stargard", az: "Starqard", pl: "Stargard", de: "Stargard", es: "Stargard", pt: "Stargard", tr: "Stargard", uk: "Старгард" } },
  { key: "Suwałki", translations: { en: "Suwalki", az: "Suvalki", pl: "Suwałki", de: "Suwalki", es: "Suwalki", pt: "Suwalki", tr: "Suwalki", uk: "Сувалки" } },
  { key: "Słupca", translations: { en: "Slupca", az: "Sluptsa", pl: "Słupca", de: "Slupca", es: "Slupca", pt: "Slupca", tr: "Slupca", uk: "Слупца" } },
  { key: "Szczecin", translations: { en: "Szczecin", az: "Şetsin", pl: "Szczecin", de: "Stettin", es: "Szczecin", pt: "Szczecin", tr: "Szczecin", uk: "Щецин" } },
  { key: "Świdnica", translations: { en: "Swidnica", az: "Şvidnitsa", pl: "Świdnica", de: "Schweidnitz", es: "Swidnica", pt: "Swidnica", tr: "Swidnica", uk: "Свідниця" } },
  { key: "Tarnobrzeg", translations: { en: "Tarnobrzeg", az: "Tarnobjeq", pl: "Tarnobrzeg", de: "Tarnobrzeg", es: "Tarnobrzeg", pt: "Tarnobrzeg", tr: "Tarnobrzeg", uk: "Тарнобжег" } },
  { key: "Tarnów", translations: { en: "Tarnow", az: "Tarnov", pl: "Tarnów", de: "Tarnau", es: "Tarnow", pt: "Tarnow", tr: "Tarnow", uk: "Тарнув" } },
  { key: "Toruń", translations: { en: "Torun", az: "Torun", pl: "Toruń", de: "Thorn", es: "Torun", pt: "Torun", tr: "Torun", uk: "Торунь" } },
  { key: "Tychy", translations: { en: "Tychy", az: "Tixi", pl: "Tychy", de: "Tichau", es: "Tychy", pt: "Tychy", tr: "Tychy", uk: "Тихи" } },
  { key: "Wałbrzych", translations: { en: "Walbrzych", az: "Valbrıx", pl: "Wałbrzych", de: "Waldenburg", es: "Walbrzych", pt: "Walbrzych", tr: "Walbrzych", uk: "Валбжих" } },
  { key: "Warszawa", translations: { en: "Warsaw", az: "Varşava", pl: "Warszawa", de: "Warschau", es: "Varsovia", pt: "Varsóvia", tr: "Varşova", uk: "Варшава" } },
  { key: "Włocławek", translations: { en: "Wloclawek", az: "Vlotslavek", pl: "Włocławek", de: "Leslau", es: "Wloclawek", pt: "Wloclawek", tr: "Wloclawek", uk: "Влоцлавек" } },
  { key: "Wrocław", translations: { en: "Wroclaw", az: "Vrotslav", pl: "Wrocław", de: "Breslau", es: "Wroclaw", pt: "Wroclaw", tr: "Wroclaw", uk: "Вроцлав" } },
  { key: "Zabrze", translations: { en: "Zabrze", az: "Zabrje", pl: "Zabrze", de: "Hindenburg", es: "Zabrze", pt: "Zabrze", tr: "Zabrze", uk: "Забже" } },
  { key: "Zakopane", translations: { en: "Zakopane", az: "Zakopane", pl: "Zakopane", de: "Zakopane", es: "Zakopane", pt: "Zakopane", tr: "Zakopane", uk: "Закопане" } },
  { key: "Zamość", translations: { en: "Zamosc", az: "Zamosç", pl: "Zamość", de: "Zamosch", es: "Zamosc", pt: "Zamosc", tr: "Zamosc", uk: "Замосць" } },
  { key: "Zgierz", translations: { en: "Zgierz", az: "Zgejş", pl: "Zgierz", de: "Zgierz", es: "Zgierz", pt: "Zgierz", tr: "Zgierz", uk: "Згеж" } },
  { key: "Zielona Góra", translations: { en: "Zielona Gora", az: "Jelona Qura", pl: "Zielona Góra", de: "Grünberg", es: "Zielona Gora", pt: "Zielona Gora", tr: "Zielona Gora", uk: "Зелена-Гура" } },
  { key: "Żary", translations: { en: "Zary", az: "Jari", pl: "Żary", de: "Sorau", es: "Zary", pt: "Zary", tr: "Zary", uk: "Жари" } },
  { key: "Żory", translations: { en: "Zory", az: "Jori", pl: "Żory", de: "Sohrau", es: "Zory", pt: "Zory", tr: "Zory", uk: "Жори" } },
  { key: "Zawiercie", translations: { en: "Zawiercie", az: "Zavertse", pl: "Zawiercie", de: "Zawiercie", es: "Zawiercie", pt: "Zawiercie", tr: "Zawiercie", uk: "Заверце" } },
  { key: "Żnin", translations: { en: "Znin", az: "Jnin", pl: "Żnin", de: "Znin", es: "Znin", pt: "Znin", tr: "Znin", uk: "Жнін" } },
  { key: "Żuromin", translations: { en: "Zuromin", az: "Juromin", pl: "Żuromin", de: "Zuromin", es: "Zuromin", pt: "Zuromin", tr: "Zuromin", uk: "Журомін" } },
  { key: "Żyrardów", translations: { en: "Zyrardow", az: "Jirardov", pl: "Żyrardów", de: "Zyrardow", es: "Zyrardow", pt: "Zyrardow", tr: "Zyrardow", uk: "Жирардув" } }
]
export const features: { key: string; translations: { en: string; az: string; pl: string; de: string; es: string; pt: string; tr: string; uk: string } }[] = [
  { key: "ABS", translations: { en: "ABS", az: "ABS", pl: "ABS", de: "ABS", es: "ABS", pt: "ABS", tr: "ABS", uk: "ABS" } },
  { key: "EBD", translations: { en: "EBD (Electronic Brake Distribution)", az: "EBD (Elektron əyləc paylanması)", pl: "EBD (Elektroniczny rozdzielacz hamowania)", de: "EBD (Elektronische Bremskraftverteilung)", es: "EBD (Distribución Electrónica de Frenado)", pt: "EBD (Distribuição Eletrônica de Frenagem)", tr: "EBD (Elektronik Fren Dağılımı)", uk: "EBD (Електронний розподіл гальмівної сили)" } },
  { key: "ESP/ESC", translations: { en: "ESP/ESC", az: "ESP/ESC", pl: "ESP/ESC", de: "ESP/ESC", es: "ESP/ESC", pt: "ESP/ESC", tr: "ESP/ESC", uk: "ESP/ESC" } },
  { key: "Traction Control", translations: { en: "Traction Control", az: "Çəkici Nəzarət", pl: "Kontrola trakcji", de: "Traktionskontrolle", es: "Control de Tracción", pt: "Controle de Tração", tr: "Çekiş Kontrolü", uk: "Контроль тяги" } },
  { key: "Airbags (Front)", translations: { en: "Airbags (Front)", az: "Airbags (Ön)", pl: "Poduszki powietrzne (przednie)", de: "Airbags (Front)", es: "Airbags (Delanteros)", pt: "Airbags (Dianteiros)", tr: "Hava Yastıkları (Ön)", uk: "Подушки безпеки (передні)" } },
  { key: "Airbags (Side)", translations: { en: "Airbags (Side)", az: "Airbags (Yan)", pl: "Poduszki powietrzne (boczne)", de: "Airbags (Seitlich)", es: "Airbags (Laterales)", pt: "Airbags (Laterais)", tr: "Hava Yastıkları (Yan)", uk: "Подушки безпеки (бічні)" } },
  { key: "Curtain Airbags", translations: { en: "Curtain Airbags", az: "Perde Airbags", pl: "Kurtyny powietrzne", de: "Kopfairbags", es: "Airbags de Cortina", pt: "Airbags de Cortina", tr: "Perde Hava Yastıkları", uk: "Шторкові подушки безпеки" } },
  { key: "Collision Warning", translations: { en: "Collision Warning", az: "Kolliziya xəbərdarlığı", pl: "Ostrzeżenie o kolizji", de: "Kollisionswarnung", es: "Advertencia de Colisión", pt: "Alerta de Colisão", tr: "Çarpışma Uyarısı", uk: "Попередження про зіткнення" } },
  { key: "Automatic Emergency Braking (AEB)", translations: { en: "Automatic Emergency Braking (AEB)", az: "Avtomatik təcili əyləc (AEB)", pl: "Automatyczne hamowanie awaryjne (AEB)", de: "Automatische Notbremse (AEB)", es: "Frenado de Emergencia Automático (AEB)", pt: "Freio de Emergência Automático (AEB)", tr: "Otomatik Acil Frenleme (AEB)", uk: "Автоматичне екстрене гальмування (AEB)" } },
  { key: "Tire Pressure Monitoring System (TPMS)", translations: { en: "Tire Pressure Monitoring System (TPMS)", az: "Təkər təzyiqi monitorinqi (TPMS)", pl: "System monitorowania ciśnienia w oponach (TPMS)", de: "Reifendruckkontrollsystem (RDKS)", es: "Sistema de Monitoreo de Presión de Neumáticos (TPMS)", pt: "Sistema de Monitoramento de Pressão dos Pneus (TPMS)", tr: "Lastik Basınç İzleme Sistemi (TPMS)", uk: "Система контролю тиску в шинах (TPMS)" } },
  { key: "Hill Descent Control", translations: { en: "Hill Descent Control", az: "Dəyişən yol köməyi (Hill Descent Control)", pl: "Kontrola zjazdu ze wzniesienia", de: "Gefällehilfe", es: "Control de Descenso en Pendientes", pt: "Controle de Descida em Declives", tr: "Yokuş İniş Kontrolü", uk: "Контроль спуску з пагорба" } },
  { key: "Blind Spot Monitoring (BSM)", translations: { en: "Blind Spot Monitoring (BSM)", az: "Ölü nöqtə monitorinqi (BSM)", pl: "Monitorowanie martwego pola (BSM)", de: "Toter-Winkel-Warner", es: "Monitor de Punto Ciego (BSM)", pt: "Monitor de Ponto Cego (BSM)", tr: "Kör Nokta Uyarı Sistemi (BSM)", uk: "Моніторинг сліпих зон (BSM)" } },
  { key: "Lane Assist", translations: { en: "Lane Assist", az: "Zolaq kömək sistemi (Lane Assist)", pl: "Asystent pasa ruchu", de: "Spurassistent", es: "Asistente de Carril", pt: "Assistente de Faixa", tr: "Şerit Asistanı", uk: "Помічник смуги руху" } },
  { key: "Lane Keeping Assist", translations: { en: "Lane Keeping Assist", az: "Zolaq saxlama yardımçısı", pl: "Asystent utrzymania pasa ruchu", de: "Spurhalteassistent", es: "Asistente de Mantenimiento de Carril", pt: "Assistente de Manutenção de Faixa", tr: "Şerit Koruma Asistanı", uk: "Помічник утримання смуги руху" } },
  { key: "Tire Pressure Monitor", translations: { en: "Tire Pressure Monitor", az: "Tire Pressure Monitor", pl: "Monitor ciśnienia w oponach", de: "Reifendruckmonitor", es: "Monitor de Presión de Neumáticos", pt: "Monitor de Pressão dos Pneus", tr: "Lastik Basınç Monitörü", uk: "Монітор тиску в шинах" } },
  { key: "Adaptive Headlights", translations: { en: "Adaptive Headlights", az: "Adaptiv faralar", pl: "Adaptacyjne reflektory", de: "Adaptives Kurvenlicht", es: "Faros Adaptativos", pt: "Faróis Adaptativos", tr: "Adaptif Farlar", uk: "Адаптивні фари" } },
  { key: "Night Vision", translations: { en: "Night Vision", az: "Gecə Görmə", pl: "Noktowizja", de: "Nachtsicht", es: "Visión Nocturna", pt: "Visão Noturna", tr: "Gece Görüş", uk: "Нічний бачення" } },
  { key: "Roll-over Protection", translations: { en: "Roll-over Protection", az: "Ters çevrilməyə qarşı qoruma", pl: "Ochrona przed dachowaniem", de: "Überschlagschutz", es: "Protección contra Vuelco", pt: "Proteção contra Capotagem", tr: "Devrilme Koruması", uk: "Захист від перекидання" } },
  { key: "Pedestrian Detection", translations: { en: "Pedestrian Detection", az: "Piyada aşkarlanması", pl: "Wykrywanie pieszych", de: "Fußgängererkennung", es: "Detección de Peatones", pt: "Detecção de Pedestres", tr: "Yaya Tespiti", uk: "Виявлення пішоходів" } },
  { key: "Driver Attention Alert", translations: { en: "Driver Attention Alert", az: "Sürücü diqqət xəbərdarlığı", pl: "Czujnik uwagi kierowcy", de: "Müdigkeitswarner", es: "Alerta de Atención del Conductor", pt: "Alerta de Atenção do Motorista", tr: "Sürücü Dikkat Uyarısı", uk: "Попередження про увагу водія" } },
  { key: "Blind Spot Intervention", translations: { en: "Blind Spot Intervention", az: "Ölü nöqtə müdaxiləsi", pl: "Interwencja martwego pola", de: "Toter-Winkel-Eingriff", es: "Intervención de Punto Ciego", pt: "Intervenção de Ponto Cego", tr: "Kör Nokta Müdahalesi", uk: "Втручання у сліпу зону" } },
  { key: "Rear Cross Traffic Alert", translations: { en: "Rear Cross Traffic Alert", az: "Arxa çarpaz trafik xəbərdarlığı", pl: "Ostrzeżenie o ruchu poprzecznym z tyłu", de: "Hinterer Querverkehrswarner", es: "Alerta de Tráfico Cruzado Trasero", pt: "Alerta de Tráfico Cruzado Traseiro", tr: "Arka Çapraz Trafik Uyarısı", uk: "Попередження про поперечний рух ззаду" } },
  { key: "ISO-FIX Child Anchors", translations: { en: "ISO-FIX Child Anchors", az: "ISO-FIX uşaq oturacağı", pl: "Kotwy ISO-FIX dla dzieci", de: "ISO-FIX-Kindersitzbefestigung", es: "Anclajes ISO-FIX para Niños", pt: "Âncoras ISO-FIX para Crianças", tr: "ISO-FIX Çocuk Koltuğu Bağlantıları", uk: "Кріплення ISO-FIX для дитячих крісел" } },
  { key: "Traffic Sign Recognition", translations: { en: "Traffic Sign Recognition", az: "Trafik nişanlarını tanıma", pl: "Rozpoznawanie znaków drogowych", de: "Verkehrszeichenerkennung", es: "Reconocimiento de Señales de Tráfico", pt: "Reconhecimento de Sinais de Trânsito", tr: "Trafik İşareti Tanıma", uk: "Розпізнавання дорожніх знаків" } },
  { key: "Manual Air Conditioning", translations: { en: "Manual Air Conditioning", az: "Kondisioner (Manuel)", pl: "Klimatyzacja manualna", de: "Manuelle Klimaanlage", es: "Aire Acondicionado Manual", pt: "Ar Condicionado Manual", tr: "Manuel Klima", uk: "Ручний кондиціонер" } },
  { key: "Dual-zone Automatic Climate", translations: { en: "Dual-zone Automatic Climate", az: "Avtomatik İqlim Nəzarəti (Dual-Zone)", pl: "Dwustrefowa klimatyzacja automatyczna", de: "Zweizonen-Klimaautomatik", es: "Clima Automático de Dos Zonas", pt: "Clima Automático de Duas Zonas", tr: "Çift Bölgeli Otomatik Klima", uk: "Двозонний автоматичний клімат-контроль" } },
  { key: "Tri-zone Automatic Climate", translations: { en: "Tri-zone Automatic Climate", az: "Avtomatik İqlim (Tri-Zone)", pl: "Trójstrefowa klimatyzacja automatyczna", de: "Dreizonen-Klimaautomatik", es: "Clima Automático de Tres Zonas", pt: "Clima Automático de Três Zonas", tr: "Üç Bölgeli Otomatik Klima", uk: "Тризонний автоматичний клімат-контроль" } },
  { key: "Heated Seats", translations: { en: "Heated Seats", az: "İsitməli oturacaqlar", pl: "Podgrzewane fotele", de: "Sitzheizung", es: "Asientos Calefaccionados", pt: "Assentos Aquecidos", tr: "Isıtmalı Koltuklar", uk: "Підігрівачі сидінь" } },
  { key: "Ventilated Seats", translations: { en: "Ventilated Seats", az: "Sərinlənən oturacaqlar", pl: "Wentylowane fotele", de: "Belüftete Sitze", es: "Asientos Ventilados", pt: "Assentos Ventilados", tr: "Havalandırmalı Koltuklar", uk: "Вентильовані сидіння" } },
  { key: "Massaging Seats", translations: { en: "Massaging Seats", az: "Masaj oturacaqları", pl: "Fotele z masażem", de: "Massagesitze", es: "Asientos con Masaje", pt: "Assentos com Massagem", tr: "Masajlı Koltuklar", uk: "Масажні сидіння" } },
  { key: "Memory Seats", translations: { en: "Memory Seats", az: "Xatırlayan oturacaqlar", pl: "Fotele z pamięcią", de: "Sitzposition mit Memory", es: "Asientos con Memoria", pt: "Assentos com Memória", tr: "Hafızalı Koltuklar", uk: "Сидіння з пам'яттю" } },
  { key: "Leather Upholstery", translations: { en: "Leather Upholstery", az: "Dəri salon", pl: "Skórzana tapicerka", de: "Lederausstattung", es: "Tapicería de Cuero", pt: "Estofamento em Couro", tr: "Deri Döşeme", uk: "Шкіряна оббивка" } },
  { key: "Fabric Upholstery", translations: { en: "Fabric Upholstery", az: "Parça salon", pl: "Tkaninowa tapicerka", de: "Stoffausstattung", es: "Tapicería de Tela", pt: "Estofamento em Tecido", tr: "Kumaş Döşeme", uk: "Тканинна оббивка" } },
  { key: "Alcantara Trim", translations: { en: "Alcantara Trim", az: "Alkantara trim", pl: "Wykończenie Alcantara", de: "Alcantara-Ausstattung", es: "Acabado en Alcantara", pt: "Acabamento em Alcântara", tr: "Alcantara Kaplama", uk: "Оздоблення алькантарою" } },
  { key: "Heated Steering Wheel", translations: { en: "Heated Steering Wheel", az: "İsitməli sükan", pl: "Podgrzewana kierownica", de: "Lenkradheizung", es: "Volante Calefaccionado", pt: "Volante Aquecido", tr: "Isıtmalı Direksiyon", uk: "Підігрів керма" } },
  { key: "Ventilated Steering Wheel", translations: { en: "Ventilated Steering Wheel", az: "Sərinlənən sükan", pl: "Wentylowana kierownica", de: "Belüftetes Lenkrad", es: "Volante Ventilado", pt: "Volante Ventilado", tr: "Havalandırmalı Direksiyon", uk: "Вентильоване кермо" } },
  { key: "Power Seats", translations: { en: "Power Seats", az: "Elektrik oturacaqlar", pl: "Elektryczne fotele", de: "Elektrische Sitze", es: "Asientos Eléctricos", pt: "Assentos Elétricos", tr: "Elektrikli Koltuklar", uk: "Електричні сидіння" } },
  { key: "Electric Lumbar Support", translations: { en: "Electric Lumbar Support", az: "Elektrik bel dəstəyi", pl: "Elektryczne wsparcie lędźwiowe", de: "Elektrische Lordosenstütze", es: "Soporte Lumbar Eléctrico", pt: "Suporte Lombar Elétrico", tr: "Elektrikli Bel Desteği", uk: "Електрична пояснична підтримка" } },
  { key: "Rear Seat Recline", translations: { en: "Rear Seat Recline", az: "Arxa oturacaq meyli", pl: "Regulacja oparcia tylnych siedzeń", de: "Rückbank neigbar", es: "Inclinación de Asientos Traseros", pt: "Inclinação dos Bancos Traseiros", tr: "Arka Koltuk Eğimi", uk: "Регулювання спинки задніх сидінь" } },
  { key: "Rear Armrest", translations: { en: "Rear Armrest", az: "Arxa qol dayağı", pl: "Tylna podłokietnik", de: "Hinterer Armlehne", es: "Reposabrazos Trasero", pt: "Apoio de Braço Traseiro", tr: "Arka Kol Dayanağı", uk: "Задній підлокітник" } },
  { key: "Rear Climate Control", translations: { en: "Rear Climate Control", az: "Arxa iqlim nəzarəti", pl: "Tylna klimatyzacja", de: "Hintere Klimaregelung", es: "Control Climático Trasero", pt: "Controle Climático Traseiro", tr: "Arka Klima Kontrolü", uk: "Задній клімат-контроль" } },
  { key: "Sunroof", translations: { en: "Sunroof", az: "Sunroof", pl: "Szyberdach", de: "Schiebedach", es: "Techo Solar", pt: "Teto Solar", tr: "Panoramik Cam Tavan", uk: "Люк" } },
  { key: "Panoramic Sunroof", translations: { en: "Panoramic Sunroof", az: "Panoramik sunroof", pl: "Panoramiczny szyberdach", de: "Panorama-Schiebedach", es: "Techo Solar Panorámico", pt: "Teto Solar Panorâmico", tr: "Panoramik Cam Tavan", uk: "Панорамний люк" } },
  { key: "Power Sunshade", translations: { en: "Power Sunshade", az: "Elektrik günəşlik", pl: "Elektryczna osłona przeciwsłoneczna", de: "Elektrische Sonnenblende", es: "Persiana Eléctrica", pt: "Persiana Elétrica", tr: "Elektrikli Güneşlik", uk: "Електрична сонцезахисна штора" } },
  { key: "Ambient Lighting", translations: { en: "Ambient Lighting", az: "Ambiyans işıqlandırması", pl: "Oświetlenie ambientowe", de: "Ambiente-Beleuchtung", es: "Iluminación Ambiental", pt: "Iluminação Ambiente", tr: "Ortam Aydınlatması", uk: "Атмосферне підсвічування" } },
  { key: "Wireless Phone Charger", translations: { en: "Wireless Phone Charger", az: "Simsiz telefon şarjı", pl: "Bezprzewodowa ładowarka do telefonu", de: "Drahtlose Handy-Ladestation", es: "Cargador Inalámbrico para Teléfono", pt: "Carregador Sem Fio para Celular", tr: "Kablosuz Telefon Şarjı", uk: "Бездротова зарядка для телефону" } },
  { key: "Cup Holders", translations: { en: "Cup Holders", az: "Stəkan tutacaqları", pl: "Przytrzymywacze kubków", de: "Getränkehalter", es: "Portavasos", pt: "Porta-copos", tr: "Kupa Tutucular", uk: "Підставки для чашок" } },
  { key: "Center Console Storage", translations: { en: "Center Console Storage", az: "Mərkəzi konsol saxlama", pl: "Schowek w konsoli środkowej", de: "Stauraum in der Mittelkonsole", es: "Almacenamiento en Consola Central", pt: "Armazenamento no Console Central", tr: "Orta Konsol Depolama", uk: "Відділення в центральній консолі" } },
  { key: "Adjustable Steering Column", translations: { en: "Adjustable Steering Column", az: "Tənzimlənən sükan sütunu", pl: "Regulowana kolumna kierownicy", de: "Verstellbare Lenksäule", es: "Columna de Dirección Ajustable", pt: "Coluna de Direção Ajustável", tr: "Ayarlanabilir Direksiyon Kolonu", uk: "Регульована колонка керма" } },
  { key: "Keyless Entry", translations: { en: "Keyless Entry", az: "Açar olmadan giriş", pl: "Wejście bezkluczykowe", de: "Keyless-Go", es: "Entrada sin Llave", pt: "Entrada sem Chave", tr: "Anahtarsız Giriş", uk: "Безключовий вхід" } },
  { key: "Push Button Start", translations: { en: "Push Button Start", az: "Düymə ilə işə salma", pl: "Przycisk start/stop", de: "Start-Stopp-Taste", es: "Encendido por Botón", pt: "Partida por Botão", tr: "Düğmeli Marş", uk: "Кнопковий запуск" } },
  { key: "Remote Start", translations: { en: "Remote Start", az: "Uzaqdan işə salma", pl: "Zdalne uruchamianie", de: "Fernstart", es: "Arranque Remoto", pt: "Partida Remota", tr: "Uzaktan Çalıştırma", uk: "Дистанційний запуск" } },
  { key: "Hands-free Tailgate", translations: { en: "Hands-free Tailgate", az: "Əllərsiz baqaj qapağı", pl: "Bezdotykowe otwieranie klapy bagażnika", de: "Handfreie Heckklappe", es: "Portón Trasero sin Manos", pt: "Porta-malas sem Mãos", tr: "Ellersiz Bagaj Kapağı", uk: "Безконтактне відкриття багажника" } },
  { key: "Power Tailgate", translations: { en: "Power Tailgate", az: "Elektrik baqaj qapağı", pl: "Elektryczna klapa bagażnika", de: "Elektrische Heckklappe", es: "Portón Trasero Eléctrico", pt: "Porta-malas Elétrico", tr: "Elektrikli Bagaj Kapağı", uk: "Електричний багажник" } },
  { key: "Soft-close Doors", translations: { en: "Soft-close Doors", az: "Yumşaq bağlanan qapılar", pl: "Miękkie zamykanie drzwi", de: "Softclose-Türen", es: "Puertas de Cierre Suave", pt: "Portas de Fechamento Suave", tr: "Yumuşak Kapanan Kapılar", uk: "Двері з м'яким закриттям" } },
  { key: "Noise Insulation Package", translations: { en: "Noise Insulation Package", az: "Səs izolyasiya paketi", pl: "Pakiet izolacji akustycznej", de: "Schalldämmungspaket", es: "Paquete de Aislamiento Acústico", pt: "Pacote de Isolamento Acústico", tr: "Ses Yalıtım Paketi", uk: "Пакет шумоізоляції" } },
  { key: "Cabin Air Purifier", translations: { en: "Cabin Air Purifier", az: "Salon hava təmizləyicisi", pl: "Oczyszczacz powietrza w kabinie", de: "Innenraum-Luftreiniger", es: "Purificador de Aire de Cabina", pt: "Purificador de Ar da Cabine", tr: "Kabin Hava Temizleyici", uk: "Очищувач повітря в салоні" } },
  { key: "Touchscreen Display", translations: { en: "Touchscreen Display", az: "Sensorlu ekran", pl: "Wyświetlacz dotykowy", de: "Touchscreen-Display", es: "Pantalla Táctil", pt: "Tela de Toque", tr: "Dokunmatik Ekran", uk: "Сенсорний екран" } },
  { key: "Apple CarPlay", translations: { en: "Apple CarPlay", az: "Apple CarPlay", pl: "Apple CarPlay", de: "Apple CarPlay", es: "Apple CarPlay", pt: "Apple CarPlay", tr: "Apple CarPlay", uk: "Apple CarPlay" } },
  { key: "Android Auto", translations: { en: "Android Auto", az: "Android Auto", pl: "Android Auto", de: "Android Auto", es: "Android Auto", pt: "Android Auto", tr: "Android Auto", uk: "Android Auto" } },
  { key: "Built-in Navigation", translations: { en: "Built-in Navigation", az: "Daxili Naviqasiya", pl: "Wbudowana nawigacja", de: "Integriertes Navigationssystem", es: "Navegación Integrada", pt: "Navegação Integrada", tr: "Dahili Navigasyon", uk: "Вбудована навігація" } },
  { key: "Bluetooth", translations: { en: "Bluetooth", az: "Bluetooth", pl: "Bluetooth", de: "Bluetooth", es: "Bluetooth", pt: "Bluetooth", tr: "Bluetooth", uk: "Bluetooth" } },
  { key: "In-car WiFi", translations: { en: "In-car WiFi", az: "Avtomobildə WiFi", pl: "WiFi w samochodzie", de: "WLAN im Auto", es: "WiFi en el Coche", pt: "WiFi no Carro", tr: "Araç İçi WiFi", uk: "Wi-Fi в автомобілі" } },
  { key: "Adaptive Sound System", translations: { en: "Adaptive Sound System", az: "Adaptiv səs sistemi", pl: "Adaptacyjny system dźwięku", de: "Adaptives Soundsystem", es: "Sistema de Sonido Adaptativo", pt: "Sistema de Som Adaptativo", tr: "Adaptif Ses Sistemi", uk: "Адаптивна аудіосистема" } },
  { key: "Premium Sound System", translations: { en: "Premium Sound System (Bose/Harman/Bang & Olufsen)", az: "Premium Səs Sistemi (Bose/Harman/Bang & Olufsen)", pl: "Premium system dźwiękowy (Bose/Harman/Bang & Olufsen)", de: "Premium-Soundsystem (Bose/Harman/Bang & Olufsen)", es: "Sistema de Sonido Premium (Bose/Harman/Bang & Olufsen)", pt: "Sistema de Som Premium (Bose/Harman/Bang & Olufsen)", tr: "Premium Ses Sistemi (Bose/Harman/Bang & Olufsen)", uk: "Преміальна аудіосистема (Bose/Harman/Bang & Olufsen)" } },
  { key: "Multiple USB Ports", translations: { en: "Multiple USB Ports", az: "Bir neçə USB portu", pl: "Wiele portów USB", de: "Mehrere USB-Anschlüsse", es: "Múltiples Puertos USB", pt: "Múltiplas Portas USB", tr: "Çoklu USB Portlar", uk: "Кілька USB-портів" } },
  { key: "12V Socket", translations: { en: "12V Socket", az: "12V priz", pl: "Gniazdo 12V", de: "12V-Steckdose", es: "Toma de 12V", pt: "Tomada 12V", tr: "12V Priz", uk: "Розетка 12V" } },
  { key: "HD Radio", translations: { en: "HD Radio", az: "HD Radio", pl: "Radio HD", de: "HD-Radio", es: "Radio HD", pt: "Rádio HD", tr: "HD Radyo", uk: "HD радіо" } },
  { key: "DAB+", translations: { en: "DAB+", az: "DAB+", pl: "DAB+", de: "DAB+", es: "DAB+", pt: "DAB+", tr: "DAB+", uk: "DAB+" } },
  { key: "Voice Recognition", translations: { en: "Voice Recognition", az: "Səs tanıma", pl: "Rozpoznawanie głosu", de: "Spracherkennung", es: "Reconocimiento de Voz", pt: "Reconhecimento de Voz", tr: "Ses Tanıma", uk: "Розпізнавання голосу" } },
  { key: "OTA Updates", translations: { en: "OTA Updates", az: "OTA Yeniləmələri", pl: "Aktualizacje OTA", de: "OTA-Updates", es: "Actualizaciones OTA", pt: "Atualizações OTA", tr: "OTA Güncellemeleri", uk: "OTA оновлення" } },
  { key: "Telematics Service", translations: { en: "Telematics Service", az: "Telematik Xidmət", pl: "Usługa telematyczna", de: "Telematikdienst", es: "Servicio de Telemetría", pt: "Serviço de Telemetria", tr: "Telematik Hizmeti", uk: "Телематичний сервіс" } },
  { key: "Connected Car Services", translations: { en: "Connected Car Services", az: "Qoşulmuş Avtomobil Xidmətləri", pl: "Usługi Connected Car", de: "Connected-Car-Dienste", es: "Servicios de Coche Conectado", pt: "Serviços de Carro Conectado", tr: "Bağlantılı Araç Hizmetleri", uk: "Послуги підключеного автомобіля" } },
  { key: "Driver Profiles", translations: { en: "Driver Profiles", az: "Sürücü profilləri", pl: "Profile kierowcy", de: "Fahrerprofile", es: "Perfiles de Conductor", pt: "Perfis do Motorista", tr: "Sürücü Profilleri", uk: "Профілі водія" } },
  { key: "Over-the-air Maps", translations: { en: "Over-the-air Maps", az: "Hava vasitəsilə xəritələr", pl: "Mapy Over-the-air", de: "Over-the-air-Karten", es: "Mapas por Aire", pt: "Mapas Over-the-air", tr: "Hava Üzerinden Haritalar", uk: "Оновлення карт по повітрю" } },
  { key: "In-car Apps", translations: { en: "In-car Apps", az: "Avtomobil tətbiqləri", pl: "Aplikacje w samochodzie", de: "Auto-Apps", es: "Aplicaciones en el Coche", pt: "Aplicativos no Carro", tr: "Araç İçi Uygulamalar", uk: "Додатки в автомобілі" } },
  { key: "Rear Entertainment System", translations: { en: "Rear Entertainment System", az: "Arxa əyləncə sistemi", pl: "Tylny system rozrywki", de: "Hinteres Unterhaltungssystem", es: "Sistema de Entretenimiento Trasero", pt: "Sistema de Entretenimento Traseiro", tr: "Arka Eğlence Sistemi", uk: "Розважальна система для задніх пасажирів" } },
  { key: "Head-up Display (HUD)", translations: { en: "Head-up Display (HUD)", az: "Baş üstü ekran (HUD)", pl: "Wyświetlacz przezierny (HUD)", de: "Head-up-Display (HUD)", es: "Pantalla de Head-up (HUD)", pt: "Display de Cabeça (HUD)", tr: "Baş Üstü Göstergesi (HUD)", uk: "Проекційний дисплей (HUD)" } },
  { key: "Instrument Cluster LCD", translations: { en: "Instrument Cluster LCD", az: "Alət paneli LCD", pl: "Wyświetlacz LCD w desce rozdzielczej", de: "LCD-Instrumententafel", es: "Panel de Instrumentos LCD", pt: "Painel de Instrumentos LCD", tr: "Gösterge Paneli LCD", uk: "LCD-панель приладів" } },
  { key: "Gesture Control", translations: { en: "Gesture Control", az: "Jestlə idarəetmə", pl: "Sterowanie gestami", de: "Gestiksteuerung", es: "Control por Gestos", pt: "Controle por Gestos", tr: "Hareket Kontrolü", uk: "Управління жестами" } },
  { key: "Wireless Mirroring", translations: { en: "Wireless Mirroring", az: "Simsiz mirroring", pl: "Bezprzewodowe mirroring", de: "Drahtloses Mirroring", es: "Mirroring Inalámbrico", pt: "Espelhamento Sem Fio", tr: "Kablosuz Yansıtma", uk: "Бездротове дзеркалення" } },
  { key: "Rear Camera", translations: { en: "Rear Camera", az: "Arxa kamera", pl: "Tylna kamera", de: "Rückfahrkamera", es: "Cámara Trasera", pt: "Câmera Traseira", tr: "Arka Kamera", uk: "Задня камера" } },
  { key: "Front Camera", translations: { en: "Front Camera", az: "Ön kamera", pl: "Przednia kamera", de: "Frontkamera", es: "Cámara Delantera", pt: "Câmera Dianteira", tr: "Ön Kamera", uk: "Передня камера" } },
  { key: "360 Degree Camera", translations: { en: "360 Degree Camera", az: "360 Dərəcə Kamera", pl: "Kamera 360 stopni", de: "360-Grad-Kamera", es: "Cámara 360 Grados", pt: "Câmera 360 Graus", tr: "360 Derece Kamera", uk: "Камера 360 градусів" } },
  { key: "Parking Sensors (Front)", translations: { en: "Parking Sensors (Front)", az: "Park sensorları (Ön)", pl: "Czujniki parkowania (przednie)", de: "Einparkhilfe vorne", es: "Sensores de Estacionamiento (Delanteros)", pt: "Sensores de Estacionamento (Dianteiros)", tr: "Park Sensörleri (Ön)", uk: "Паркувальні датчики (передні)" } },
  { key: "Parking Sensors (Rear)", translations: { en: "Parking Sensors (Rear)", az: "Park sensorları (Arxa)", pl: "Czujniki parkowania (tylne)", de: "Einparkhilfe hinten", es: "Sensores de Estacionamiento (Traseros)", pt: "Sensores de Estacionamento (Traseiros)", tr: "Park Sensörleri (Arka)", uk: "Паркувальні датчики (задні)" } },
  { key: "Autonomous Parking", translations: { en: "Autonomous Parking", az: "Avtonom park", pl: "Autonomiczne parkowanie", de: "Autonomes Einparken", es: "Estacionamiento Autónomo", pt: "Estacionamento Autônomo", tr: "Otonom Park", uk: "Автономне паркування" } },
  { key: "Rear View Mirror Camera", translations: { en: "Rear View Mirror Camera", az: "Arxa güzgü kamerası", pl: "Kamera w lusterku wstecznym", de: "Rückspiegelkamera", es: "Cámara en Espejo Retrovisor", pt: "Câmera no Espelho Retrovisor", tr: "Dikiz Aynası Kamerası", uk: "Камера в дзеркалі заднього виду" } },
  { key: "Top-view Camera", translations: { en: "Top-view Camera", az: "Üst baxış kamerası", pl: "Kamera widoku z góry", de: "Top-View-Kamera", es: "Cámara de Vista Superior", pt: "Câmera de Vista Superior", tr: "Üstten Görünüm Kamerası", uk: "Камера з видом зверху" } },
  { key: "Park Assist", translations: { en: "Park Assist", az: "Park köməyi", pl: "Asystent parkowania", de: "Parkassistent", es: "Asistente de Estacionamiento", pt: "Assistente de Estacionamento", tr: "Park Asistanı", uk: "Помічник паркування" } },
  { key: "Trailer Assist", translations: { en: "Trailer Assist", az: "Treyler köməyi", pl: "Asystent przyczepy", de: "Anhängerassistent", es: "Asistente de Remolque", pt: "Assistente de Reboque", tr: "Römork Asistanı", uk: "Помічник причепа" } },
  { key: "Bird's Eye View", translations: { en: "Bird's Eye View", az: "Quş baxışı", pl: "Widok z lotu ptaka", de: "Vogelperspektive", es: "Vista de Ojo de Pájaro", pt: "Vista de Olho de Pássaro", tr: "Kuş Bakışı Görünüm", uk: "Вигляд з висоти пташиного польоту" } },
  { key: "Rear Cross Traffic Braking", translations: { en: "Rear Cross Traffic Braking", az: "Arxa çarpaz trafik əyləcləri", pl: "Hamowanie przy ruchu poprzecznym z tyłu", de: "Bremsen bei Querverkehr hinten", es: "Frenado de Tráfico Cruzado Trasero", pt: "Freio de Tráfico Cruzado Traseiro", tr: "Arka Çapraz Trafik Frenlemesi", uk: "Гальмування при поперечному русі ззаду" } },
  { key: "LED Headlights", translations: { en: "LED Headlights", az: "LED faralar", pl: "Reflektory LED", de: "LED-Scheinwerfer", es: "Faros LED", pt: "Faróis LED", tr: "LED Farlar", uk: "LED фари" } },
  { key: "Xenon Headlights", translations: { en: "Xenon Headlights", az: "Xenon faralar", pl: "Reflektory ksenonowe", de: "Xenon-Scheinwerfer", es: "Faros de Xenón", pt: "Faróis de Xenônio", tr: "Xenon Farlar", uk: "Ксенонові фари" } },
  { key: "Matrix LED", translations: { en: "Matrix LED", az: "Matrix LED", pl: "Matrix LED", de: "Matrix-LED", es: "LED Matrix", pt: "LED Matrix", tr: "Matrix LED", uk: "Матричні LED" } },
  { key: "Adaptive LED Headlights", translations: { en: "Adaptive LED Headlights", az: "Adaptiv LED faralar", pl: "Adaptacyjne reflektory LED", de: "Adaptive LED-Scheinwerfer", es: "Faros LED Adaptativos", pt: "Faróis LED Adaptativos", tr: "Adaptif LED Farlar", uk: "Адаптивні LED фари" } },
  { key: "Daytime Running Lights (DRL)", translations: { en: "Daytime Running Lights (DRL)", az: "Gündüz işıqları (DRL)", pl: "Światła do jazdy dziennej (DRL)", de: "Tagfahrlicht (DRL)", es: "Luces de Conducción Diurna (DRL)", pt: "Luzes de Rodagem Diurna (DRL)", tr: "Gündüz Farı (DRL)", uk: "Денні ходові вогні (DRL)" } },
  { key: "Automatic Headlights", translations: { en: "Automatic Headlights", az: "Avtomatik faralar", pl: "Automatyczne światła", de: "Automatische Scheinwerfer", es: "Faros Automáticos", pt: "Faróis Automáticos", tr: "Otomatik Farlar", uk: "Автоматичні фари" } },
  { key: "Cornering Lights", translations: { en: "Cornering Lights", az: "Künc işıqları", pl: "Światła do jazdy po łuku", de: "Kurvenlicht", es: "Luces de Curva", pt: "Luzes de Curva", tr: "Viraj Işıkları", uk: "Поворотні вогні" } },
  { key: "Fog Lights", translations: { en: "Fog Lights", az: "Duman işıqları", pl: "Światła przeciwmgielne", de: "Nebelscheinwerfer", es: "Luces Antiniebla", pt: "Faróis de Neblina", tr: "Sis Farları", uk: "Противотуманні фари" } },
  { key: "LED Tail Lights", translations: { en: "LED Tail Lights", az: "LED arxa işıqlar", pl: "Tylne światła LED", de: "LED-Rückleuchten", es: "Luces Traseras LED", pt: "Luzes Traseiras LED", tr: "LED Arka Işıklar", uk: "LED задні ліхтарі" } },
  { key: "Roof Rails", translations: { en: "Roof Rails", az: "Tavan relsləri", pl: "Relingi dachowe", de: "Dachreling", es: "Barras de Techo", pt: "Barras de Teto", tr: "Tavan Rayları", uk: "Рейлінги на даху" } },
  { key: "Panoramic Roof", translations: { en: "Panoramic Roof", az: "Panoramik tavan", pl: "Panoramiczny dach", de: "Panoramadach", es: "Techo Panorámico", pt: "Teto Panorâmico", tr: "Panoramik Tavan", uk: "Панорамний дах" } },
  { key: "Power Folding Mirrors", translations: { en: "Power Folding Mirrors", az: "Elektrik qatlanan güzgülər", pl: "Elektrycznie składane lusterka", de: "Elektrisch anklappbare Spiegel", es: "Espejos Plegables Eléctricos", pt: "Espelhos Dobráveis Elétricos", tr: "Elektrikli Katlanır Aynalar", uk: "Електричні складні дзеркала" } },
  { key: "Heated Mirrors", translations: { en: "Heated Mirrors", az: "İsitməli güzgülər", pl: "Podgrzewane lusterka", de: "Beheizbare Spiegel", es: "Espejos Calefaccionados", pt: "Espelhos Aquecidos", tr: "Isıtmalı Aynalar", uk: "Підігрівачі дзеркал" } },
  { key: "Auto-dimming Mirrors", translations: { en: "Auto-dimming Mirrors", az: "Avtomatik qaralayan güzgülər", pl: "Lusterka z przyciemnianiem automatycznym", de: "Automatisch abblendende Spiegel", es: "Espejos con Antideslumbramiento Automático", pt: "Espelhos com Escurecimento Automático", tr: "Otomatik Kararan Aynalar", uk: "Автоматично затемнювані дзеркала" } },
  { key: "Rain-sensing Wipers", translations: { en: "Rain-sensing Wipers", az: "Yağış sensorlu silecekler", pl: "Czujnik deszczu", de: "Regensensor", es: "Limpiaparabrisas con Sensor de Lluvia", pt: "Limpadores com Sensor de Chuva", tr: "Yağmur Sensörlü Silecekler", uk: "Дворники з датчиком дощу" } },
  { key: "Electric Windows", translations: { en: "Electric Windows", az: "Elektrik pəncərələr", pl: "Elektryczne szyby", de: "Elektrische Fensterheber", es: "Ventanas Eléctricas", pt: "Vidros Elétricos", tr: "Elektrikli Camlar", uk: "Електричні вікна" } },
  { key: "Privacy Glass", translations: { en: "Privacy Glass", az: "Məxfilik şüşəsi", pl: "Szyby prywatności", de: "Privatsphäre-Glas", es: "Cristal de Privacidad", pt: "Vidro de Privacidade", tr: "Gizlilik Camı", uk: "Тоноване скло" } },
  { key: "Tinted Glass", translations: { en: "Tinted Glass", az: "Tonlaşdırılmış şüşə", pl: "Przyciemniane szyby", de: "Getönte Scheiben", es: "Cristal Tintado", pt: "Vidro Fumê", tr: "Boyalı Cam", uk: "Затемнене скло" } },
  { key: "Sunshade", translations: { en: "Sunshade", az: "Günəşlik", pl: "Oslona przeciwsłoneczna", de: "Sonnenschutz", es: "Parasol", pt: "Quebra-sol", tr: "Güneşlik", uk: "Сонцезахисний козирок" } },
  { key: "Spoiler", translations: { en: "Spoiler", az: "Spoiler", pl: "Spoiler", de: "Spoiler", es: "Spoiler", pt: "Spoiler", tr: "Spoiler", uk: "Спойлер" } },
  { key: "Diffuser", translations: { en: "Diffuser", az: "Difüzor", pl: "Dyfuzor", de: "Diffusor", es: "Difusor", pt: "Difusor", tr: "Difüzör", uk: "Дифузор" } },
  { key: "Sport Mode", translations: { en: "Sport Mode", az: "Sport rejimi", pl: "Tryb sportowy", de: "Sportmodus", es: "Modo Deportivo", pt: "Modo Esportivo", tr: "Spor Modu", uk: "Спортивний режим" } },
  { key: "Eco Mode", translations: { en: "Eco Mode", az: "Eco rejimi", pl: "Tryb eco", de: "Eco-Modus", es: "Modo Eco", pt: "Modo Econômico", tr: "Eko Mod", uk: "Еко режим" } },
  { key: "Adaptive Suspension", translations: { en: "Adaptive Suspension", az: "Adaptiv Asqı", pl: "Zawieszenie adaptacyjne", de: "Adaptives Fahrwerk", es: "Suspensión Adaptativa", pt: "Suspensão Adaptativa", tr: "Adaptif Süspansiyon", uk: "Адаптивна підвіска" } },
  { key: "Air Suspension", translations: { en: "Air Suspension", az: "Hava asqısı", pl: "Zawieszenie pneumatyczne", de: "Luftfederung", es: "Suspensión Neumática", pt: "Suspensão a Ar", tr: "Havalı Süspansiyon", uk: "Пневматична підвіска" } },
  { key: "Magnetic Ride Control", translations: { en: "Magnetic Ride Control", az: "Maqnit sürüş nəzarəti", pl: "Kontrola zawieszenia magnetycznego", de: "Magnetisches Fahrwerk", es: "Control Magnético de Suspensión", pt: "Controle Magnético de Suspensão", tr: "Manyetik Süspansiyon Kontrolü", uk: "Магнітна підвіска" } },
  { key: "Limited Slip Differential", translations: { en: "Limited Slip Differential", az: "Məhdud sürüş diferensialı", pl: "Dyferencjał o ograniczonym poślizgu", de: "Sperrdifferential", es: "Diferencial de Deslizamiento Limitado", pt: "Diferencial de Deslizamento Limitado", tr: "Sınırlı Kaydırmalı Diferansiyel", uk: "Диференціал з обмеженим тертям" } },
  { key: "Active Aero", translations: { en: "Active Aero", az: "Aktiv aero", pl: "Aktywna aerodynamika", de: "Aktive Aerodynamik", es: "Aerodinámica Activa", pt: "Aerodinâmica Ativa", tr: "Aktif Aerodinamik", uk: "Активна аеродинаміка" } },
  { key: "Launch Control", translations: { en: "Launch Control", az: "Launch Control", pl: "Launch Control", de: "Launch Control", es: "Control de Lanzamiento", pt: "Controle de Lançamento", tr: "Kalkış Kontrolü", uk: "Контроль старту" } },
  { key: "Torque Vectoring", translations: { en: "Torque Vectoring", az: "Tork vektorlaşması", pl: "Vectoring momentu obrotowego", de: "Torque Vectoring", es: "Vectorización de Par", pt: "Vectorização de Torque", tr: "Tork Vektörleme", uk: "Векторування крутного моменту" } },
  { key: "Four Wheel Drive", translations: { en: "Four Wheel Drive", az: "Dörd təkərdən sürüş", pl: "Napęd na cztery koła", de: "Allradantrieb", es: "Tracción a las Cuatro Ruedas", pt: "Tração nas Quatro Rodas", tr: "Dört Çeker", uk: "Повний привід" } },
  { key: "All Wheel Drive", translations: { en: "All Wheel Drive", az: "Bütün təkərlərdən sürüş", pl: "Napęd na wszystkie koła", de: "Allradantrieb", es: "Tracción en Todas las Ruedas", pt: "Tração Integral", tr: "Tam Çeker", uk: "Повний привід" } },
  { key: "Rear Wheel Drive", translations: { en: "Rear Wheel Drive", az: "Arxa təkərdən sürüş", pl: "Napęd na tylne koła", de: "Hinterradantrieb", es: "Tracción Trasera", pt: "Tração Traseira", tr: "Arka Çeker", uk: "Задній привід" } },
  { key: "Front Wheel Drive", translations: { en: "Front Wheel Drive", az: "Ön təkərdən sürüş", pl: "Napęd na przednie koła", de: "Frontantrieb", es: "Tracción Delantera", pt: "Tração Dianteira", tr: "Ön Çeker", uk: "Передній привід" } },
  { key: "Adjustable Ride Height", translations: { en: "Adjustable Ride Height", az: "Tənzimlənən sürüş hündürlüyü", pl: "Regulowana wysokość zawieszenia", de: "Verstellbare Fahrhöhe", es: "Altura de Conducción Ajustable", pt: "Altura de Condução Ajustável", tr: "Ayarlanabilir Süspansiyon Yüksekliği", uk: "Регульована висота підвіски" } },
  { key: "Performance Brakes", translations: { en: "Performance Brakes", az: "Performans əyləcləri", pl: "Hamulce wydajnościowe", de: "Leistungsbremsen", es: "Frenos de Alto Rendimiento", pt: "Freios de Alta Performance", tr: "Performans Frenleri", uk: "Продуктивні гальма" } },
  { key: "Brembo Brakes", translations: { en: "Brembo Brakes", az: "Brembo əyləcləri", pl: "Hamulce Brembo", de: "Brembo-Bremsen", es: "Frenos Brembo", pt: "Freios Brembo", tr: "Brembo Frenler", uk: "Гальма Brembo" } },
  { key: "Ceramic Brakes", translations: { en: "Ceramic Brakes", az: "Keramik əyləclər", pl: "Hamulce ceramiczne", de: "Keramikbremsen", es: "Frenos Cerámicos", pt: "Freios Cerâmicos", tr: "Seramik Frenler", uk: "Керамічні гальма" } },
  { key: "Regenerative Braking", translations: { en: "Regenerative Braking", az: "Regenerativ əyləc", pl: "Hamowanie rekuperacyjne", de: "Rekuperationsbremse", es: "Frenado Regenerativo", pt: "Freio Regenerativo", tr: "Reküperatif Frenleme", uk: "Рекуперативне гальмування" } },
  { key: "Start/Stop System", translations: { en: "Start/Stop System", az: "Start/Stop Sistemi", pl: "System Start/Stop", de: "Start-Stopp-System", es: "Sistema Start/Stop", pt: "Sistema Start/Stop", tr: "Start/Stop Sistemi", uk: "Система старт-стоп" } },
  { key: "Alloy Wheels", translations: { en: "Alloy Wheels", az: "Döküm disklər", pl: "Aluminiowe felgi", de: "Alufelgen", es: "Llantas de Aleación", pt: "Rodas de Liga", tr: "Alaşım Jantlar", uk: "Легкосплавні диски" } },
  { key: "Run-flat Tires", translations: { en: "Run-flat Tires", az: "Run-flat təkərlər", pl: "Opony run-flat", de: "Run-Flat-Reifen", es: "Neumáticos Run-flat", pt: "Pneus Run-flat", tr: "Run-flat Lastikler", uk: "Непроколювані шини" } },
  { key: "Tire Repair Kit", translations: { en: "Tire Repair Kit", az: "Təkər təmir dəsti", pl: "Zestaw do naprawy opon", de: "Reifenreparaturset", es: "Kit de Reparación de Neumáticos", pt: "Kit de Reparo de Pneus", tr: "Lastik Tamir Kit", uk: "Набір для ремонту шин" } },
  { key: "Wheel Size 15\"", translations: { en: "Wheel Size 15\"", az: "Təkər Ölçüsü 15\"", pl: "Rozmiar felg 15\"", de: "Felgengröße 15\"", es: "Tamaño de Rueda 15\"", pt: "Tamanho da Roda 15\"", tr: "Jant Boyutu 15\"", uk: "Розмір коліс 15\"" } },
  { key: "Wheel Size 16\"", translations: { en: "Wheel Size 16\"", az: "Təkər Ölçüsü 16\"", pl: "Rozmiar felg 16\"", de: "Felgengröße 16\"", es: "Tamaño de Rueda 16\"", pt: "Tamanho da Roda 16\"", tr: "Jant Boyutu 16\"", uk: "Розмір коліс 16\"" } },
  { key: "Wheel Size 17\"", translations: { en: "Wheel Size 17\"", az: "Təkər Ölçüsü 17\"", pl: "Rozmiar felg 17\"", de: "Felgengröße 17\"", es: "Tamaño de Rueda 17\"", pt: "Tamanho da Roda 17\"", tr: "Jant Boyutu 17\"", uk: "Розмір коліс 17\"" } },
  { key: "Wheel Size 18\"", translations: { en: "Wheel Size 18\"", az: "Təkər Ölçüsü 18\"", pl: "Rozmiar felg 18\"", de: "Felgengröße 18\"", es: "Tamaño de Rueda 18\"", pt: "Tamanho da Roda 18\"", tr: "Jant Boyutu 18\"", uk: "Розмір коліс 18\"" } },
  { key: "Wheel Size 19\"", translations: { en: "Wheel Size 19\"", az: "Təkər Ölçüsü 19\"", pl: "Rozmiar felg 19\"", de: "Felgengröße 19\"", es: "Tamaño de Rueda 19\"", pt: "Tamanho da Roda 19\"", tr: "Jant Boyutu 19\"", uk: "Розмір коліс 19\"" } },
  { key: "Wheel Size 20\"", translations: { en: "Wheel Size 20\"", az: "Təkər Ölçüsü 20\"", pl: "Rozmiar felg 20\"", de: "Felgengröße 20\"", es: "Tamaño de Rueda 20\"", pt: "Tamanho da Roda 20\"", tr: "Jant Boyutu 20\"", uk: "Розмір коліс 20\"" } },
  { key: "Wheel Size 21\"", translations: { en: "Wheel Size 21\"", az: "Təkər Ölçüsü 21\"", pl: "Rozmiar felg 21\"", de: "Felgengröße 21\"", es: "Tamaño de Rueda 21\"", pt: "Tamanho da Roda 21\"", tr: "Jant Boyutu 21\"", uk: "Розмір коліс 21\"" } },
  { key: "Snow Tires Included", translations: { en: "Snow Tires Included", az: "Qış təkərləri daxil", pl: "Zimowe opony w zestawie", de: "Winterreifen inklusive", es: "Neumáticos de Nieve Incluidos", pt: "Pneus de Neve Incluídos", tr: "Kış Lastikleri Dahil", uk: "Зимові шини в комплекті" } },
  { key: "Off-road Tires", translations: { en: "Off-road Tires", az: "Off-road təkərlər", pl: "Opony off-road", de: "Geländereifen", es: "Neumáticos Off-road", pt: "Pneus Off-road", tr: "Off-road Lastikler", uk: "Позашляхові шини" } },
  { key: "Sport Tires", translations: { en: "Sport Tires", az: "Sport təkərlər", pl: "Opony sportowe", de: "Sportreifen", es: "Neumáticos Deportivos", pt: "Pneus Esportivos", tr: "Spor Lastikler", uk: "Спортивні шини" } },
  { key: "Spare Wheel", translations: { en: "Spare Wheel", az: "Ehtiyat təkər", pl: "Koło zapasowe", de: "Reserverad", es: "Rueda de Repuesto", pt: "Roda Sobressalente", tr: "Stepne", uk: "Запасне колесо" } },
  { key: "Roof Box Compatible", translations: { en: "Roof Box Compatible", az: "Tavan qutusu ilə uyğundur", pl: "Kompatybilny z boksem dachowym", de: "Dachbox-kompatibel", es: "Compatible con Caja de Techo", pt: "Compatível com Caixa de Teto", tr: "Tavan Kutusu Uyumlu", uk: "Сумісний з багажником на даху" } },
  { key: "Tow Hitch", translations: { en: "Tow Hitch", az: "Çəkmə bükümü", pl: "Hak holowniczy", de: "Anhängerkupplung", es: "Enganche de Remolque", pt: "Engate de Reboque", tr: "Çeki Demiri", uk: "Фаркоп" } },
  { key: "Tow Package", translations: { en: "Tow Package", az: "Çəkmə paketi", pl: "Pakiet holowniczy", de: "Anhängerkupplungspaket", es: "Paquete de Remolque", pt: "Pacote de Reboque", tr: "Çeki Paketi", uk: "Комплект для буксирування" } },
  { key: "Fold-flat Rear Seats", translations: { en: "Fold-flat Rear Seats", az: "Düzləşdirilə bilən arxa oturacaqlar", pl: "Składane tylne siedzenia", de: "Umklappbare Rücksitze", es: "Asientos Traseros Abatibles", pt: "Bancos Traseiros Rebatíveis", tr: "Düz Katlanır Arka Koltuklar", uk: "Складні задні сидіння" } },
  { key: "Underfloor Storage", translations: { en: "Underfloor Storage", az: "Altlıq saxlama", pl: "Schowek pod podłogą", de: "Unterboden-Stauraum", es: "Almacenamiento bajo el Suelo", pt: "Armazenamento sob o Piso", tr: "Zemin Altı Depolama", uk: "Відділення під підлогою" } },
  { key: "Hands-free Liftgate", translations: { en: "Hands-free Liftgate", az: "Əllərsiz baqaj qapağı", pl: "Bezdotykowe otwieranie klapy bagażnika", de: "Handfreie Heckklappe", es: "Portón Trasero sin Manos", pt: "Porta-malas sem Mãos", tr: "Ellersiz Bagaj Kapağı", uk: "Безконтактне відкриття багажника" } },
  { key: "Remote Trunk Release", translations: { en: "Remote Trunk Release", az: "Uzaqdan baqaj açma", pl: "Zdalenie otwierany bagażnik", de: "Fernöffnung Kofferraum", es: "Apertura Remota del Maletero", pt: "Abertura Remota do Porta-malas", tr: "Uzaktan Bagaj Açma", uk: "Дистанційне відкриття багажника" } },
  { key: "Adjustable Cargo Floor", translations: { en: "Adjustable Cargo Floor", az: "Tənzimlənən yük döşəməsi", pl: "Regulowana podłoga bagażnika", de: "Verstellbare Ladefläche", es: "Suelo de Carga Ajustable", pt: "Piso de Carga Ajustável", tr: "Ayarlanabilir Bagaj Tabanı", uk: "Регульована підлога багажного відділення" } },
  { key: "Cargo Net", translations: { en: "Cargo Net", az: "Yük toru", pl: "Siatka bagażowa", de: "Ladungsnetz", es: "Red de Carga", pt: "Rede de Carga", tr: "Bagaj Filesi", uk: "Сітка для багажу" } },
  { key: "Bike Rack Prep", translations: { en: "Bike Rack Prep", az: "Velosiped daşıyıcı hazırlığı", pl: "Przygotowanie do montażu uchwytu na rowery", de: "Fahrradträger-Vorbereitung", es: "Preparación para Portabicicletas", pt: "Preparação para Suporte de Bicicleta", tr: "Bisiklet Rampası Hazırlığı", uk: "Підготовка для велосипедного держака" } },
  { key: "Trailer Hitch", translations: { en: "Trailer Hitch", az: "Treyler çəkməsi", pl: "Hak przyczepy", de: "Anhängerkupplung", es: "Enganche de Remolque", pt: "Engate de Reboque", tr: "Römork Çeki Demiri", uk: "Причіпний пристрій" } },
  { key: "Dual-zone Climate", translations: { en: "Dual-zone Climate", az: "İki zonalı iqlim", pl: "Dwustrefowa klimatyzacja", de: "Zweizonen-Klima", es: "Clima de Dos Zonas", pt: "Clima de Duas Zonas", tr: "Çift Bölgeli Klima", uk: "Двозонний клімат-контроль" } },
  { key: "Tri-zone Climate", translations: { en: "Tri-zone Climate", az: "Üç zonalı iqlim", pl: "Trójstrefowa klimatyzacja", de: "Dreizonen-Klima", es: "Clima de Tres Zonas", pt: "Clima de Três Zonas", tr: "Üç Bölgeli Klima", uk: "Тризонний клімат-контроль" } },
  { key: "Cabin Pre-heater", translations: { en: "Cabin Pre-heater", az: "Salon əvvəlcədən qızdırıcı", pl: "Podgrzewacz postojowy", de: "Standheizung", es: "Precalentador de Cabina", pt: "Pré-aquecedor de Cabine", tr: "Kabin Ön Isıtıcı", uk: "Передгірник салону" } },
  { key: "Eco Driving Indicator", translations: { en: "Eco Driving Indicator", az: "Eco sürüş göstəricisi", pl: "Wskaźnik eco drivingu", de: "Eco-Fahr-Anzeige", es: "Indicador de Conducción Eco", pt: "Indicador de Condução Econômica", tr: "Eko Sürüş Göstergesi", uk: "Індикатор еко-водіння" } },
  { key: "Low Emissions", translations: { en: "Low Emissions", az: "Aşağı emissiya", pl: "Niska emisja", de: "Niedrige Emissionen", es: "Bajas Emisiones", pt: "Baixas Emissões", tr: "Düşük Emisyon", uk: "Низькі викиди" } },
  { key: "Euro 6 Compliant", translations: { en: "Euro 6 Compliant", az: "Euro 6 standartına uyğun", pl: "Zgodny z Euro 6", de: "Euro-6-konform", es: "Cumple con Euro 6", pt: "Conformidade Euro 6", tr: "Euro 6 Uyumlu", uk: "Відповідає стандарту Євро-6" } },
  { key: "ULEZ Compliant", translations: { en: "ULEZ Compliant", az: "ULEZ standartına uyğun", pl: "Zgodny z ULEZ", de: "ULEZ-konform", es: "Cumple con ULEZ", pt: "Conformidade ULEZ", tr: "ULEZ Uyumlu", uk: "Відповідає стандарту ULEZ" } },
  { key: "AdBlue System", translations: { en: "AdBlue System", az: "AdBlue sistemi", pl: "System AdBlue", de: "AdBlue-System", es: "Sistema AdBlue", pt: "Sistema AdBlue", tr: "AdBlue Sistemi", uk: "Система AdBlue" } },
  { key: "Particulate Filter", translations: { en: "Particulate Filter", az: "Hissəcik filtri", pl: "Filtr cząstek stałych", de: "Partikelfilter", es: "Filtro de Partículas", pt: "Filtro de Partículas", tr: "Partikül Filtresi", uk: "Фільтр частинок" } },
  { key: "CO2 Low Emission", translations: { en: "CO2 Low Emission", az: "CO2 aşağı emissiya", pl: "Niska emisja CO2", de: "CO2-Niedrigemission", es: "Baja Emisión de CO2", pt: "Baixa Emissão de CO2", tr: "Düşük CO2 Emisyonu", uk: "Низькі викиди CO2" } },
  { key: "Adaptive Cruise Control", translations: { en: "Adaptive Cruise Control", az: "Adaptiv kruiz nəzarəti", pl: "Adaptacyjny tempomat", de: "Adaptive Geschwindigkeitsregelung", es: "Control de Crucero Adaptativo", pt: "Controle de Cruzeiro Adaptativo", tr: "Adaptif Hız Sabitleyici", uk: "Адаптивний круїз-контроль" } },
  { key: "Full-Speed Adaptive Cruise", translations: { en: "Full-Speed Adaptive Cruise", az: "Tam sürətli adaptiv kruiz", pl: "Adaptacyjny tempomat pełnego zakresu", de: "Vollgeschwindigkeits-Adaptivregler", es: "Crucero Adaptativo a Velocidad Completa", pt: "Controle de Cruzeiro Adaptativo de Velocidade Total", tr: "Tam Hız Adaptif Hız Sabitleyici", uk: "Адаптивний круїз-контроль на повній швидкості" } },
  { key: "Traffic Jam Assist", translations: { en: "Traffic Jam Assist", az: "Tıxac köməyi", pl: "Asystent korkowy", de: "Stauassistent", es: "Asistente de Atascos", pt: "Assistente de Engarrafamento", tr: "Trafik Sıkışıklığı Asistanı", uk: "Помічник у заторах" } },
  { key: "Highway Assist", translations: { en: "Highway Assist", az: "Avtomobil yolu köməyi", pl: "Asystent autostradowy", de: "Autobahnassistent", es: "Asistente de Autopista", pt: "Assistente de Rodovia", tr: "Otoyol Asistanı", uk: "Помічник на автомагістралі" } },
  { key: "Autonomous Emergency Steering", translations: { en: "Autonomous Emergency Steering", az: "Avtonom təcili sükan", pl: "Autonomiczne awaryjne kierowanie", de: "Autonome Notlenkung", es: "Dirección de Emergencia Autónoma", pt: "Direção de Emergência Autônoma", tr: "Otonom Acil Direksiyon", uk: "Автономне екстрене кермування" } },
  { key: "Automatic Lane Change", translations: { en: "Automatic Lane Change", az: "Avtomatik zolaq dəyişməsi", pl: "Automatyczna zmiana pasa", de: "Automatischer Spurwechsel", es: "Cambio Automático de Carril", pt: "Mudança Automática de Faixa", tr: "Otomatik Şerit Değiştirme", uk: "Автоматична зміна смуги" } },
  { key: "Hands-free Driving Mode", translations: { en: "Hands-free Driving Mode", az: "Əllərsiz sürüş rejimi", pl: "Tryb jazdy bez użycia rąk", de: "Handfreier Fahrmodus", es: "Modo de Conducción sin Manos", pt: "Modo de Condução sem Mãos", tr: "Ellersiz Sürüş Modu", uk: "Режим безручного водіння" } },
  { key: "Driver Monitoring", translations: { en: "Driver Monitoring", az: "Sürücü monitorinqi", pl: "Monitorowanie kierowcy", de: "Fahrerüberwachung", es: "Monitoreo del Conductor", pt: "Monitoramento do Motorista", tr: "Sürücü İzleme", uk: "Моніторинг водія" } },
  { key: "Child Seat Recognition", translations: { en: "Child Seat Recognition", az: "Uşaq oturacağı tanınması", pl: "Rozpoznawanie fotelika dziecięcego", de: "Kindersitzerkennung", es: "Reconocimiento de Silla de Niño", pt: "Reconhecimento de Cadeirinha", tr: "Çocuk Koltuğu Tanıma", uk: "Розпізнавання дитячого крісла" } },
  { key: "Rear Occupant Alert", translations: { en: "Rear Occupant Alert", az: "Arxa sərnişin xəbərdarlığı", pl: "Alert o pasażerach z tyłu", de: "Hinterer Insassenalarm", es: "Alerta de Ocupante Trasero", pt: "Alerta de Ocupante Traseiro", tr: "Arka Yolcu Uyarısı", uk: "Попередження про задніх пасажирів" } },
  { key: "Floor Mats (All-weather)", translations: { en: "Floor Mats (All-weather)", az: "Məxmər döşəmələr (Hər hava üçün)", pl: "Wykładziny podłogowe (całoroczne)", de: "Fußmatten (Ganzjahres)", es: "Alfombrillas (Todo Clima)", pt: "Tapetes (Todo Clima)", tr: "Zemin Halıları (Hava Koşullarına Dayanıklı)", uk: "Килимки (всепоганні)" } },
  { key: "Cargo Cover", translations: { en: "Cargo Cover", az: "Yük örtüyü", pl: "Pokrowiec bagażnika", de: "Ladeabdeckung", es: "Cubierta de Carga", pt: "Cobertura de Carga", tr: "Bagaj Örtüsü", uk: "Чохол для багажу" } },
  { key: "Illuminated Sill Plates", translations: { en: "Illuminated Sill Plates", az: "İşıqlı eşik lövhələri", pl: "Podświetlane progi", de: "Beleuchtte Schweller", es: "Placas de Umbral Iluminadas", pt: "Placas de Soleira Iluminadas", tr: "Aydınlatmalı Eşik Plakaları", uk: "Підсвічувані пороги" } },
  { key: "Ambient Lighting Customizable", translations: { en: "Ambient Lighting Customizable", az: "Ambiyans işıqlandırması özelleştirilebilir", pl: "Konfigurowalne oświetlenie ambientowe", de: "Anpassbare Ambiente-Beleuchtung", es: "Iluminación Ambiental Personalizable", pt: "Iluminação Ambiente Personalizável", tr: "Özelleştirilebilir Ortam Aydınlatması", uk: "Налаштовуване атмосферне підсвічування" } },
  { key: "Wood Trim", translations: { en: "Wood Trim", az: "Ağac trimi", pl: "Wykończenie drewniane", de: "Holzapplikationen", es: "Acabado en Madera", pt: "Acabamento em Madeira", tr: "Ahşap Kaplama", uk: "Дерев'яне оздоблення" } },
  { key: "Carbon Fiber Trim", translations: { en: "Carbon Fiber Trim", az: "Karbon lif trimi", pl: "Wykończenie z włókna węglowego", de: "Kohlefaser-Applikationen", es: "Acabado en Fibra de Carbono", pt: "Acabamento em Fibra de Carbono", tr: "Karbon Fiber Kaplama", uk: "Вуглецевове волокно" } },
  { key: "Aluminum Pedals", translations: { en: "Aluminum Pedals", az: "Alüminium pedallar", pl: "Aluminiowe pedały", de: "Aluminium-Pedale", es: "Pedales de Aluminio", pt: "Pedais de Alumínio", tr: "Alüminyum Pedallar", uk: "Алюмінієві педалі" } },
  { key: "Sport Steering Wheel", translations: { en: "Sport Steering Wheel", az: "Sport sükan", pl: "Sportowa kierownica", de: "Sportlenkrad", es: "Volante Deportivo", pt: "Volante Esportivo", tr: "Spor Direksiyon", uk: "Спортивне кермо" } },
  { key: "Heated Rear Seats", translations: { en: "Heated Rear Seats", az: "İsitməli arxa oturacaqlar", pl: "Podgrzewane tylne siedzenia", de: "Beheizbare Rücksitze", es: "Asientos Traseros Calefaccionados", pt: "Assentos Traseiros Aquecidos", tr: "Isıtmalı Arka Koltuklar", uk: "Підігрівачі задніх сидінь" } },
  { key: "Ventilated Rear Seats", translations: { en: "Ventilated Rear Seats", az: "Sərinlənən arxa oturacaqlar", pl: "Wentylowane tylne siedzenia", de: "Belüftete Rücksitze", es: "Asientos Traseros Ventilados", pt: "Assentos Traseiros Ventilados", tr: "Havalandırmalı Arka Koltuklar", uk: "Вентильовані задні сидіння" } },
  { key: "Refrigerated Glovebox", translations: { en: "Refrigerated Glovebox", az: "Soyuduculu əl cibi", pl: "Schowek na rękawiczki z chłodzeniem", de: "Gekühlter Handschuhfach", es: "Guatera Refrigerada", pt: "Porta-luvas Refrigerado", tr: "Soğutmalı Torpido", uk: "Охолоджуваний бардачок" } },
  { key: "Alarm System", translations: { en: "Alarm System", az: "Alarm Sistemi", pl: "System alarmowy", de: "Alarmanlage", es: "Sistema de Alarma", pt: "Sistema de Alarme", tr: "Alarm Sistemi", uk: "Сигналізація" } },
  { key: "Immobilizer", translations: { en: "Immobilizer", az: "Immobilizer", pl: "Immobilizer", de: "Wegfahrsperre", es: "Inmovilizador", pt: "Imobilizador", tr: "Immobilizer", uk: "Іммобілайзер" } },
  { key: "GPS Tracking", translations: { en: "GPS Tracking", az: "GPS izləmə", pl: "Śledzenie GPS", de: "GPS-Ortung", es: "Seguimiento GPS", pt: "Rastreamento GPS", tr: "GPS Takip", uk: "GPS-трекінг" } },
  { key: "Wheel Locking Bolts", translations: { en: "Wheel Locking Bolts", az: "Təkər kilidi boltları", pl: "Śruby zabezpieczające felgi", de: "Radschraubensicherung", es: "Pernos de Seguridad para Ruedas", pt: "Parafusos de Segurança para Rodas", tr: "Jant Kilitleme Cıvataları", uk: "Гвинти-секретки" } },
  { key: "PIN to Drive", translations: { en: "PIN to Drive", az: "PIN ilə sürüş", pl: "PIN do jazdy", de: "PIN zum Fahren", es: "PIN para Conducir", pt: "PIN para Dirigir", tr: "Sürüş için PIN", uk: "PIN для керування" } },
  { key: "Remote Vehicle Disable", translations: { en: "Remote Vehicle Disable", az: "Uzaqdan avtomobil söndürmə", pl: "Zdalne wyłączenie pojazdu", de: "Fernabschaltung des Fahrzeugs", es: "Desactivación Remota del Vehículo", pt: "Desativação Remota do Veículo", tr: "Uzaktan Araç Devre Dışı Bırakma", uk: "Дистанційне вимикання автомобіля" } },
  { key: "Keyless-Go", translations: { en: "Keyless-Go", az: "Açar olmadan getmə", pl: "Keyless-Go", de: "Schlüsselloses Startsystem", es: "Arranque sin llave", pt: "Partida sem chave", tr: "Anahtarsız Başlatma", uk: "Keyless-Go" } },
  { key: "Valet Mode", translations: { en: "Valet Mode", az: "Valet rejimi", pl: "Tryb valet", de: "Valet-Modus", es: "Modo Valet", pt: "Modo manobrista", tr: "Vale Modu", uk: "Режим валета" } },
  { key: "Anti-theft Wheel Locks", translations: { en: "Anti-theft Wheel Locks", az: "Oğurluğa qarşı təkər kilidləri", pl: "Blokady antykradzieżowe kół", de: "Diebstahlsicherungsradschlösser", es: "Cierres antirrobo para ruedas", pt: "Trancas antirroubo para rodas", tr: "Hırsızlığa Karşı Tekerlek Kilidi", uk: "Протиугонні гвинти" } },
  { key: "Central Locking", translations: { en: "Central Locking", az: "Mərkəzi kilid", pl: "Centralny zamek", de: "Zentralverriegelung", es: "Cierre centralizado", pt: "Trancamento central", tr: "Merkezi Kilit", uk: "Центральний замок" } },
  { key: "Hill Start Assist", translations: { en: "Hill Start Assist", az: "Yamacda start köməyi", pl: "Asystent ruszania pod górę", de: "Berganfahrhilfe", es: "Asistente de arranque en pendiente", pt: "Assistência de partida em rampas", tr: "Yokuş Kalkış Desteği", uk: "Помічник старту на підйомі" } },
  { key: "Skid Plates", translations: { en: "Skid Plates", az: "Alt qoruyucu lövhələr", pl: "Płyty ochronne podwozia", de: "Schutzplatten", es: "Placas protectoras", pt: "Placas de proteção", tr: "Alt Koruyucu Levhalar", uk: "Захисні пластини" } },
  { key: "Off-road Mode", translations: { en: "Off-road Mode", az: "Off-road rejimi", pl: "Tryb off-road", de: "Gelände-Modus", es: "Modo todoterreno", pt: "Modo off-road", tr: "Arazi Modu", uk: "Позашляховий режим" } },
  { key: "4x4 Low Range", translations: { en: "4x4 Low Range", az: "4x4 aşağı sürüş", pl: "4x4 niski bieg", de: "4x4 Untersetzung", es: "4x4 marchas bajas", pt: "4x4 Baixa", tr: "4x4 Düşük Vites", uk: "Понижена передача 4x4" } },
  { key: "Trailer Sway Control", translations: { en: "Trailer Sway Control", az: "Treyler yellənmə nəzarəti", pl: "Kontrola kołysania przyczepy", de: "Anhänger-Überschlagskontrolle", es: "Control de oscilación del remolque", pt: "Controle de oscilação do reboque", tr: "Römork Salınım Kontrolü", uk: "Контроль гойдання причепа" } },
  { key: "Rear Differential Lock", translations: { en: "Rear Differential Lock", az: "Arxa diferensial kilidi", pl: "Blokada tylnego dyferencjału", de: "Hinterachs-Sperrdifferential", es: "Bloqueo de diferencial trasero", pt: "Travamento do diferencial traseiro", tr: "Arka Diferansiyel Kilidi", uk: "Блокування заднього диференціала" } },
  { key: "Winter Package", translations: { en: "Winter Package", az: "Qış paketi", pl: "Pakiet zimowy", de: "Winterpaket", es: "Paquete de invierno", pt: "Pacote de inverno", tr: "Kış Paketi", uk: "Зимовий пакет" } },
  { key: "Summer Package", translations: { en: "Summer Package", az: "Yay paketi", pl: "Pakiet letni", de: "Sommerpaket", es: "Paquete de verano", pt: "Pacote de verão", tr: "Yaz Paketi", uk: "Літній пакет" } },
  { key: "Sport Package", translations: { en: "Sport Package", az: "Sport paketi", pl: "Pakiet sportowy", de: "Sportpaket", es: "Paquete deportivo", pt: "Pacote esportivo", tr: "Spor Paketi", uk: "Спортивний пакет" } },
  { key: "Technology Package", translations: { en: "Technology Package", az: "Texnologiya paketi", pl: "Pakiet technologiczny", de: "Technologiepaket", es: "Paquete tecnológico", pt: "Pacote de tecnologia", tr: "Teknoloji Paketi", uk: "Технологічний пакет" } },
  { key: "Luxury Package", translations: { en: "Luxury Package", az: "Lüks paketi", pl: "Pakiet luksusowy", de: "Luxuspaket", es: "Paquete de lujo", pt: "Pacote de luxo", tr: "Lüks Paketi", uk: "Розкішний пакет" } },
  { key: "Cold Climate Package", translations: { en: "Cold Climate Package", az: "Soyuq iqlim paketi", pl: "Pakiet zimny klimat", de: "Kälteklimapaket", es: "Paquete clima frío", pt: "Pacote clima frio", tr: "Soğuk İklim Paketi", uk: "Пакет для холодного клімату" } },
  { key: "Premium Paint", translations: { en: "Premium Paint", az: "Premium boyama", pl: "Premium lakier", de: "Premium-Lackierung", es: "Pintura premium", pt: "Pintura premium", tr: "Premium Boya", uk: "Преміальна фарба" } },
  { key: "Extended Warranty", translations: { en: "Extended Warranty", az: "Uzadılmış zəmanət", pl: "Przedłużona gwarancja", de: "Verlängerte Garantie", es: "Garantía extendida", pt: "Garantia estendida", tr: "Uzatılmış Garanti", uk: "Розширена гарантія" } },
  { key: "Service Plan Included", translations: { en: "Service Plan Included", az: "Xidmət planı daxil", pl: "Plan serwisowy w zestawie", de: "Serviceplan enthalten", es: "Plan de servicio incluido", pt: "Plano de serviço incluído", tr: "Servis Planı Dahil", uk: "Сервісний план включено" } },
  { key: "Dealer Installed Options", translations: { en: "Dealer Installed Options", az: "Satıcı quraşdırılmış seçimlər", pl: "Opcje montowane u dealera", de: "Vom Händler installierte Optionen", es: "Opciones instaladas por concesionario", pt: "Opções instaladas pelo concessionário", tr: "Bayi Kurulumu Seçenekleri", uk: "Опції, встановлені дилером" } },
  { key: "Owner's Manual in English/AZ", translations: { en: "Owner's Manual in English/AZ", az: "İstifadəçi təlimatı İngilis/AZ", pl: "Instrukcja obsługi po angielsku/azersku", de: "Betriebsanleitung auf Englisch/AZ", es: "Manual del propietario en inglés/AZ", pt: "Manual do proprietário em inglês/AZ", tr: "Kullanıcı Kılavuzu İngilizce/AZ", uk: "Інструкція англійською/азербайджанською" } },
  { key: "First Aid Kit", translations: { en: "First Aid Kit", az: "Təcili yardım dəsti", pl: "Apteczka pierwszej pomocy", de: "Erste-Hilfe-Set", es: "Botiquín de primeros auxilios", pt: "Kit de primeiros socorros", tr: "İlk Yardım Çantası", uk: "Аптечка" } },
  { key: "Fire Extinguisher", translations: { en: "Fire Extinguisher", az: "Yanğınsöndürən", pl: "Gaśnica", de: "Feuerlöscher", es: "Extintor de incendios", pt: "Extintor de incêndio", tr: "Yangın Söndürücü", uk: "Вогнегасник" } },
  { key: "Roadside Assistance Included", translations: { en: "Roadside Assistance Included", az: "Yolda kömək daxil", pl: "Assistance drogowy w zestawie", de: "Pannenhilfe enthalten", es: "Asistencia en carretera incluida", pt: "Assistência na estrada incluída", tr: "Yolda Yardım Dahil", uk: "Дорожня допомога включена" } },
];

export const status = [
  { key: "premium", translations: { en: "Premium", az: "Premium", pl: "Premium", de: "Premium", es: "Premium", pt: "Premium", tr: "Premium", uk: "Преміум" } },
  { key: "standart", translations: {   en: "Standard",   az: "Standart",   pl: "Standard",   de: "Standard",   es: "Estándar",   pt: "Padrão",   tr: "Standart",   uk: "Стандарт" } },
  { key: "sold", translations: {   en: "Sold",   az: "Satılıb",   pl: "Sprzedany",   de: "Verkauft",   es: "Vendido",   pt: "Vendido",   tr: "Satıldı",   uk: "Продано" } },
]


export const years = Array.from({ length: 100 }, (_, i) => new Date().getFullYear() - i)

